### ISSUE TITLE
Unable to open object

### ISSUE THREAD

**Issue by Zumbalamambo** [cvg/Hierarchical-Localization#10]
I tried `pipeline_Aachen`. I executed the following chunk of code,

```
localize_sfm.main(
    reference_sfm / 'model',
    dataset / 'queries/*_time_queries_with_intrinsics.txt',
    loc_pairs,
    outputs / f"{feature_conf['output']}.h5",
    outputs / f"{feature_conf['output']}_{matcher_conf['output']}_{loc_pairs.stem}.h5",
    results,
    covisibility_clustering=False)  # not required with SuperPoint+SuperGlue
```

However, it throws the following error

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-23-f42806d6b032> in <module>
>       5     outputs / f"{feature_conf['output']}.h5",
>       6     outputs / f"{feature_conf['output']}_{matcher_conf['output']}_{loc_pairs.stem}.h5",
> ----> 7     results)  # not required with SuperPoint+SuperGlue
> 
> ~/Workspace/Python/Hierarchical-Localization/hloc/localize_sfm.py in main(reference_sfm, queries, retrieval, features, matches, results, ransac_thresh, covisibility_clustering)
>     162             ret, mkpq, mp3d, mp3d_ids, num_matches, map_ = pose_from_cluster(
>     163                 qname, qinfo, db_ids, db_images, points3D,
> --> 164                 feature_file, match_file, thresh=ransac_thresh)
>     165             # logging.info(f'# inliers: {ret["num_inliers"]}')
>     166 
> 
> ~/Workspace/Python/Hierarchical-Localization/hloc/localize_sfm.py in pose_from_cluster(qname, qinfo, db_ids, db_images, points3D, feature_file, match_file, thresh)
>      48 def pose_from_cluster(qname, qinfo, db_ids, db_images, points3D,
>      49                       feature_file, match_file, thresh):
> ---> 50     kpq = feature_file[qname]['keypoints'].__array__()
>      51     kp_idx_to_3D = defaultdict(list)
>      52     kp_idx_to_3D_to_db = defaultdict(lambda: defaultdict(list))
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> ~/.conda/envs/slam/lib/python3.7/site-packages/h5py/_hl/group.py in __getitem__(self, name)
>     262                 raise ValueError("Invalid HDF5 object reference")
>     263         else:
> --> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>     265 
>     266         otype = h5i.get_type(oid)
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py/h5o.pyx in h5py.h5o.open()
> 
> KeyError: 'Unable to open object (component not found)'

Any fixes? :)

**Comment by Skydes** [comment]
Are you able to open and inspect the feature file? Something like:
```python
import h5py
file = h5py.File(outputs / f"{feature_conf['output']}.h5", 'r')
print(file.keys())
```

If not, there was a problem when creating the file - maybe the export was stopped and started again.

**Comment by Zumbalamambo** [comment]
@Skydes I might have to redo the model creation. Looks like its broken. I have another doubt.

I used [extract_features.py](https://github.com/cvg/Hierarchical-Localization/blob/869dcd44ca08bd68b73fff0324dd3cc8d89ead59/hloc/extract_features.py) to create a h5 database containing image_name and descriptor using `d2net-ss` .




I used [pair_from_retrieval.py](https://github.com/cvg/Hierarchical-Localization/blob/869dcd44ca08bd68b73fff0324dd3cc8d89ead59/hloc/pairs_from_retrieval.py#L38) to retrieve the matches. However,  you are using a key called "global_descriptor"  which is not found in `d2net-ss` .

Also I see that you are creating a tensor from the numpy array as in this [code](https://github.com/cvg/Hierarchical-Localization/blob/869dcd44ca08bd68b73fff0324dd3cc8d89ead59/hloc/pairs_from_retrieval.py#L39) . However, I get `ValueError: all input arrays must have the same shape` error when I do so which I suppose is because I'm using a wrong feature extractor since "global_descriptor" is not found as well as the descriptors are of different shapes. May I know which feature extractor is being used?

**Comment by Skydes** [comment]
`pair_from_retrieval.py` does not retrieve the matches. It computes a list of potential matching images using image retrieval, and thus requires global descriptors. These are not computed by D2-Net and are thus not in the feature file. Please read the papers linked in the README and my reply to your previous issue https://github.com/cvg/Hierarchical-Localization/issues/7. **I will not provide support beyond the tools offered in this toolbox.**

**Comment by rAm1n** [comment]
I was facing a similar issue and the problem was with the dataset as I was using images from version 1_1. The correct dataset should be downloded from the following link: https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/images/
