### ISSUE TITLE
run the pipeline of aachen dataset,  died with <Signals.SIGKILL: 9>

### ISSUE THREAD

**Issue by angiend** [cvg/Hierarchical-Localization#100]
when i run "CUDA_VISIBLE_DEVICES=1  python3 pipeline_Aachen.py " ,an error is there.
who could tell me why is this ,thanks 

![Screenshot from 2021-09-17 15-13-14](https://user-images.githubusercontent.com/39428557/133740823-4054b92f-9549-4a8f-99f9-314364d51b6b.png)

**Comment by Skydes** [comment]
The process as been killed, most likely because of insufficient RAM.

**Comment by angiend** [comment]
thanks for your reply.
my computer memory is 32g, and the whole process used about %18 (~ 6g) , far from the limitation.
i tested many times, always crash this location, would you give me  some advice?thanks.

i tested by the docker envs, build by the next command
$ docker build -t hloc:latest .

**Comment by Skydes** [comment]
What happens if you run the corresponding COLMAP command from the command line?

**Comment by angiend** [comment]
thanks，i got it .
