### ISSUE TITLE
Visual localization evaluation on the InLoc benchmark.

### ISSUE THREAD

**Issue by Qing-WANG-KIT** [cvg/Hierarchical-Localization#103]
Hi, thanks for your great work.
In your paper, you said that you used open-sourced localization pipeline HLoc  with the matches extracted by LoFTR.

Which weights do you use on the InLoc benchmark, indoor  or outdoor?

In the evaluation on the InLoc benchmark, how did you set the relevant parameters, such as the size of the input images, the matching threshold, etc.?

**Comment by Skydes** [comment]
Please refer to the [corresponding notebook](https://nbviewer.jupyter.org/github/cvg/Hierarchical-Localization/blob/master/pipeline_InLoc.ipynb) for such details:

- We used the weights of the outdoor SuperGlue model, trained on MegaDepth
- The extraction parameters are described in the corresponding config entry
https://github.com/cvg/Hierarchical-Localization/blob/ad139dc9c066d83312a99f3c77632caa311ad849/hloc/extract_features.py#L55-L66
