### ISSUE TITLE
I've got a problem with pairs from retrieval 

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#104]
![pb img](https://user-images.githubusercontent.com/88375996/136689340-65922d18-0169-4375-a467-53bb79559f7e.png)
I'm not understand what happened to pairs from retrieval step. please help

**Comment by Skydes** [comment]
Are you performing retrieval of queries against reference images? Some explanation of the call arguments:
- `query_prefix="query"` means that you expect the name of all query images to start with `query`;
- `db_model=reference_sfm` means that the script fetches the names of the references images from the images in the COLMAP mode `reference_sfm`.

The reference image `28140.jpg` is in the SfM model but not in the HDF5 file of global descriptors. `extract_features` was likely called on an incorrect folder that does not match the root of the SfM image names.
