### ISSUE TITLE
Questions about running pipeline_SfM.ipynb

### ISSUE THREAD

**Issue by xdw-123** [cvg/Hierarchical-Localization#105]
Hello, Dear Author, Your research has benefited me a lot, but I see in your introduction that the final result of SFM has absolute coordinates (WGS84), but I run pipeline_SfM.ipynb as relative coordinates and don't know what to do? You have good suggestions.

**Comment by Skydes** [comment]
The absolute poses are expressed in the reference frame of the SfM reconstruction; e.g. it could assign the origin to the location of the first image. These are not georeferenced WGS84 coordinates. I think that COLMAP can geoalign the model with [the `model_aligner` command](https://github.com/colmap/colmap/issues/98) if GPS measurements are available (they are often stored in the EXIF data). hloc does not provide this capability but feel free to contribute via a PR!
