### ISSUE TITLE
The result of robotcar season dataset

### ISSUE THREAD

**Issue by aruba01** [cvg/Hierarchical-Localization#107]
Thank you for great work. I run the robotcar pipeline with initial settings, but the result of night is quiet different from reported, while the result of day is similar(As shown in following figure). How can I reproduce your result. By the way, the result of your robotcar pipeline is about v1 or v2?
![NL)L6` (ESLJHVGC %I7I A](https://user-images.githubusercontent.com/47864285/137629913-2e8cf2a3-6f12-4e02-a46b-68a4ea6e1407.png)

**Comment by aruba01** [comment]
> Hi @aruba01, The pipeline is for the v1 but should also work for the v2. The results reported [here](https://www.visuallocalization.net/details/11963/) are based on per-location and per-camera retrieval. The pipeline in the main branch does not provide this feature [(there is a TODO)](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/RobotCar/pipeline.py#L91) but [some previous code here](https://github.com/cvg/Hierarchical-Localization/blob/robotcar/pipelines/RobotCar/robotcar_pairs_from_retrieval.py) can do this. It could be used as is or might need to be adapted - I haven't had time to look into it but a PR is welcome.

Thank you for your prompt reply, I have tried the per-localtion and per-camera pipeline successfully. Now I have a new problem in the robotcar pipeline (in the master branch), it may be a bug. I run the pipeline with the configure `feature_conf = extract_features.confs['sift']` and `matcher_conf = match_features.confs['NN-ratio']`, it will wrong when match features between query images and database (as shown in following figure). The configure [r2d2 and NN-ratio] and [superpoint and NN-ratio] is ok.
![image](https://user-images.githubusercontent.com/47864285/138068102-f7be5097-544f-4e25-b2e0-6db14d805314.png)

**Comment by rishabhramteke** [comment]
> Thank you for great work. I run the robotcar pipeline with initial settings, but the result of night is quiet different from reported, while the result of day is similar(As shown in following figure). How can I reproduce your result. By the way, the result of your robotcar pipeline is about v1 or v2? ![NL)L6` (ESLJHVGC %I7I A](https://user-images.githubusercontent.com/47864285/137629913-2e8cf2a3-6f12-4e02-a46b-68a4ea6e1407.png

@aruba01  How did get this localization accuracy results? I ran the pipeline completely on robotcar but it just says Done at the end and didn't provide these numbers.

**Comment by aruba01** [comment]
@rishabhramteke There will be a text file named `RobotCar_hloc_superpoint+superglue_netvlad20-percam-perloc.txt` in the `outputs` file folder. The text file contains the localization result for per image. You can submission the text file to [visuallocalization.net](https://www.visuallocalization.net/) and you will get the accuracy results.

**Comment by rishabhramteke** [comment]
Okay. I got it. Thank you so much for your help

**Comment by rishabhramteke** [comment]
@aruba01 How do i get the detailed results for all the subsets like dawn, dusk?
It only shows all day or all night result

**Comment by Skydes** [comment]
Seems to have been fixed by https://github.com/cvg/Hierarchical-Localization/pull/125.
