### ISSUE TITLE
Need a guide

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#109]
Dear Sarlin
I have some question 
1.After I got localization output  the pkl file. It already finished? 
2.In the .txt file it includes names of query images and other 7 values. Those 7 values are rotation matrix and Translation vector, Am I understand it correctly? 
3.How can I visualize localization in 3D model?(already have .pkl result file)

**Comment by Skydes** [comment]
The localization is completed when both pickle and text files are dumped. The format of the text file is:
```
image_name qw qx qy qz tx ty tz
```
The pose is expressed as quaternion `qw qx qy qz` and camera translation `tx ty tz` in the COLMAP coordinate system, i.e. from the world to camera frame.

I haven't yet released any tools for visualization. You can try to either:
1) Add the query poses to the reference SfM model and visualize it with the COLMAP GUI; or
3) Use a generic 3D plotting tool like plotly to draw camera frustums [(example here)](https://github.com/cvg/pixloc/blob/master/pixloc/visualization/viz_3d.py).

**Comment by mrKornWij** [comment]
> The localization is completed when both pickle and text files are dumped. The format of the text file is:
> 
> ```
> image_name qw qx qy qz tx ty tz
> ```
> 
> The pose is expressed as quaternion `qw qx qy qz` and camera translation `tx ty tz` in the COLMAP coordinate system, i.e. from the world to camera frame.
> 
> I haven't yet released any tools for visualization. You can try to either:
> 
>     1. Add the query poses to the reference SfM model and visualize it with the COLMAP GUI; or
> 
>     2. Use a generic 3D plotting tool like plotly to draw camera frustums [(example here)](https://github.com/cvg/pixloc/blob/master/pixloc/visualization/viz_3d.py).

and How could I do a performance testing on model?
