### ISSUE TITLE
Compare two images in the Robotcar dataset

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#112]
The visualization.py file tries to find the database images with the most inlier matches with respect to the query image. But how can i select this to compare two images of my choice? Did anyone work on this or modify the visualization.py file to do that?

**Comment by Skydes** [comment]
You can
1. load the keypoints from the h5 feature file
2. load the matches between the two images of interest
3. read the images from disk
4. plot with `plot_images` and `plot_matches`

**Comment by rishabhramteke** [comment]
For the step two, we should have matches between two images but there is only overcast-reference.db so how can I compare an image from night image set with an image from dawn image set?

**Comment by Skydes** [comment]
You can match them with image pairs generated using image retrieval between the two conditions.
