### ISSUE TITLE
The slices of Extended-CMU dataset

### ISSUE THREAD

**Issue by aruba01** [cvg/Hierarchical-Localization#113]
It's my first time to use this dataset. I noticed that the CMU pipeline only test on `TEST_SLICES = [2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 18, 19, 20, 21]`. Does it mean that other slices is not required? In addtion, do the final localization result require me to manually splice each text file in test_slices?

**Comment by Skydes** [comment]
The other slices are training slices: the ground truth query poses are publicly released so they are not used in the evaluation.

**Comment by aruba01** [comment]
Does it mean that the ground truth sfm model is reconstructed from the other slices and the test slice's reference model is submap of the truth sfm model?

**Comment by Skydes** [comment]
There is one SfM model for each slice and it is reconstructed from reference images, whose pose are always publicly available, for both training and test slices.

**Comment by aruba01** [comment]
Thanks for your timely reply!
