### ISSUE TITLE
Robotcar Dataset only has overcast-reference.db and not other database files

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#114]
Robotcar Dataset only has overcast-reference.db and it doesn't have other database files like night.db or dusk.db, etc.
I wanted to compare two images from the same dusk set for inlier matching features but the visualization code only compares a given imput image with images from the overcast-reference image set. Is there a possible way to visualize images from same sets like dusk, night,etc. ?

**Comment by Skydes** [comment]
You can perform image retrieval between different query conditions, match the features, and visualize the correspondences. The poses are not publicly released so you cannot triangulate an SfM model and estimate absolute poses. To filter out incorrect matches, you can instead estimate relative poses via pycolmap's [essential_matrix_estimation](https://github.com/mihaidusmanu/pycolmap/blob/master/essential_matrix.cc) and check the inliers.

**Comment by rishabhramteke** [comment]
How can use this pipeline to test my own images? 
I have removed a few objects from the robotcar dusk images manually and now I want to compare this images with the overcast-reference images. Do I need to run the whole pipeline again or is there a shorcut since the model is already trained?
