### ISSUE TITLE
Query in visualisation 

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#115]
visualization.visualize_sfm_2d(reference_sfm, images, n=1, color_by='track_length')

In this part of the pipeline, these feature keypoints were generated using only superpoint right?
Or is it superpoint + superglue?

I wanted to only visualise the result of superpoint algorithm.

**Comment by rishabhramteke** [comment]
This configuration was used
feature_conf = extract_features.confs['superpoint_aachen']
matcher_conf = match_features.confs['superglue']

**Comment by Skydes** [comment]
2D points (and thus 2D observations in the SfM models) are computed by SuperPoints and matches are computed by SuperGlue (so they only impact the 3D structure).
