### ISSUE TITLE
have an error in reconstruction steps

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#116]
![image](https://user-images.githubusercontent.com/88375996/139894344-e3a10656-1a07-4aa2-bfdc-092a007eaa16.png)
normally I can use this sfm pipeline without an error but this time it came up like this.

**Comment by Skydes** [comment]
1. Can you please show the full error traceback?
2. We recently introduced 2 commits that the impact reconstruction, 69755a69076567993b1facc19d0a57464a5ff03b and 967764cad2a3ab706f3955b437782c8860f63203, can you try to revert either of them?

**Comment by mrKornWij** [comment]
![image](https://user-images.githubusercontent.com/88375996/139927837-dbf8c88d-239e-4432-bd52-74fced96ffca.png)
@skyde here

**Comment by mrKornWij** [comment]
I already solve it i just remove reconstruction.py and replace it again

**Comment by mrKornWij** [comment]
thank you so much

**Comment by mrKornWij** [comment]
@skyde I tried to run again but it shown the result like this
![image](https://user-images.githubusercontent.com/88375996/139940807-f30cba28-088e-44b1-b33f-b91ea1e0b374.png)

**Comment by mrKornWij** [comment]
Normally this code can be used but now it can't I don't know what really happens?

**Comment by Skydes** [comment]
You are using an old commit, most likely b9c622ae2fb48d95d8f59f887e4e1db11b095a42. Can you please pull the latest changes and run the whole process again, including (if you can) the matching?

**Comment by mrKornWij** [comment]
@Skydes  I have tried it. Is this  one working?
![image](https://user-images.githubusercontent.com/88375996/140094615-217777a0-3e3f-424b-93e7-7c9602c19698.png)

**Comment by Skydes** [comment]
This seems to work yes.

**Comment by mrKornWij** [comment]
just wait for it thanks a lot!!
