### ISSUE TITLE
problem with point_triangulator

### ISSUE THREAD

**Issue by aruba01** [cvg/Hierarchical-Localization#117]
I have read some former issue about point_triangulator, but my problem seems be different from them.
The error happened when I use the robotcar branch with SIFT. The following is the log:
![9{02` 5D@7$9{L1$WGP)}CB](https://user-images.githubusercontent.com/47864285/140245926-88995e3f-3e5d-49da-8e70-ec70f320378d.png)

**Comment by Skydes** [comment]
This probably means that your machine ran out of memory - could you monitor the available RAM when the process runs?
