### ISSUE TITLE
Run the pipeline on nuScenes dataset

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#119]
I wanted to test this Hierarchical localization pipeline on nuScenes dataset. Is it possible to do so or is this pipeline not supported for it? If yes, can you give me the procedure on how I can do that?

**Comment by Skydes** [comment]
You will need to convert the camera poses to an empty COLMAP model and follow the same remaining steps as the other datasets. For an example on how to build an empty model, see the script of the 4Seasons dataset: https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/4Seasons/prepare_reference.py#L37
