### ISSUE TITLE
problem with localization

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#120]
I've got this error 
![image](https://user-images.githubusercontent.com/88375996/140695255-62f5b225-4134-4034-8042-65f54e19c066.png)

**Comment by Skydes** [comment]
It seems that for one query all retrieved images are not in the SfM model - why? Can you check that they were part of the image list given to the reconstruction/triangulation? To fix the issue, you could add:
https://github.com/cvg/Hierarchical-Localization/blob/69755a69076567993b1facc19d0a57464a5ff03b/hloc/localize_sfm.py#L131-L136
```python
if len(db_ids) == 0:
    logging.warning('Cannot localize query %s: no reference in the database.', qname)
    continue
```

**Comment by Skydes** [comment]
@mrKornWij Please confirm that the suggested fix resolves the issue.

**Comment by mrKornWij** [comment]
sorry for late reply , thank you for your help it was resolved
