### ISSUE TITLE
Value Error in Visualization

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#122]
I sometimes get this error and sometimes I don't. So, I haven't been able to understand why I get this.
I run this : 
string1 = 'dawn/left/1418722074607820.jpg'
visualization.visualize_loc(
    results, images, reference_sfm, n=1, top_k_db=1, prefix=string1, seed=1)

ValueError                                Traceback (most recent call last)
<ipython-input-2-dc00241ebc19> in <module>
      9     string1 = string1[0:32]
     10     #print(string1)
---> 11     visualization.visualize_loc(
     12         results, images, reference_sfm, n=1, top_k_db=1, prefix=string1, seed=1)

~/Hierarchical-Localization/hloc/visualization.py in visualize_loc(results, image_dir, sfm_model, top_k_db, selected, n, seed, prefix, dpi)
     72         if prefix:
     73             queries = [q for q in queries if q.startswith(prefix)]
---> 74         selected = random.Random(seed).sample(queries, n)
     75         print(selected)
     76     is_sfm = sfm_model is not None

/usr/lib/python3.8/random.py in sample(self, population, k)
    361         n = len(population)
    362         if not 0 <= k <= n:
--> 363             raise ValueError("Sample larger than population or is negative")
    364         result = [None] * k
    365         setsize = 21        # size of a small set minus size of an empty list

ValueError: Sample larger than population or is negative

**Comment by Skydes** [comment]
You are trying to visualize more images (`n`) than there are queries in the localization logs. Try to replace
https://github.com/cvg/Hierarchical-Localization/blob/d3f155d0587376a6fd0395ea36125016160fa448/hloc/visualization.py#L69
by 
```python
selected = random.Random(seed).sample(queries, min(n, len(queries)))
```

**Comment by rishabhramteke** [comment]
I am using the visualization file on AWS without jupyter notebook. How can I save these visualization images in a folder?
