### ISSUE TITLE
How to evaluate the localization results on my own dataset

### ISSUE THREAD

**Issue by jc3342** [cvg/Hierarchical-Localization#126]
Hello, thanks for your great work !
I already got the localization results on my own dataset following these steps:
a. Construct a 3d model by colmap
b. Run pairs_from_retrieval.py
c. Extract features from images and run localize_sfm.py
Now my question is how can I evaluate the localization results. What I have right now include:
1. 3d model constructed from db images by colmap
2. Localization results for query images. 
   "Image qw qx qy qz tx ty tz"
3. Groundtruth for both db images and query images given by GPS. 

Can someone help me with this? Thanks very much !

**Comment by patelajaychh** [comment]
@jc3342 can you please share how ground truth poses for db and query images were created using GPS?

**Comment by Skydes** [comment]
@jc3342 I don't have much experience with GPS but here is my take. You probably need to
1. recover the metric scale of the SfM model
  - COLMAP can do this with the model aligner: https://colmap.github.io/faq.html#geo-registration
  - Pick a local metric coordinate system (e.g. EPSG), project the GPS coordinates to it (e.g. with `pyproj`), create the text file, run the aligner.
2. infer metric GT camera centers of the queries: simply project the GPS coordinates to the same coordinate system, and use the result of the model aligner to transform the estimated 6-DoF query poses.

**Comment by jc3342** [comment]
> @jc3342 can you please share how ground truth poses for db and query images were created using GPS?

Sure! We know the GPS position (latitude, longitude, altitude and roll, pitch, yaw) for each image. Then we can convert it into any predefined coordinate. Is it clear?

**Comment by patelajaychh** [comment]
> > @jc3342 can you please share how ground truth poses for db and query images were created using GPS?
> 
> Sure! We know the GPS position (latitude, longitude, altitude and roll, pitch, yaw) for each image. Then we can convert it into any predefined coordinate. Is it clear?   

Thanks for quick reply!

Can you explain the conversation process as well? Refer to code tool if any?
