### ISSUE TITLE
Ground truth of robotcar

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#129]
Hi. Do you have the ground truth file of robotcar v1? The visuallocalization.net submission gives me average localization accuracy on all images.  But I want to test out the accuracy of every single image and find out which test cases are failing.

**Comment by Skydes** [comment]
No ground truth is available for any of the datasets of visuallocalization.net. Algorithms can only be evaluated through the submission systems. This prevents any overfitting. If you want to mine difficult queries, I suggest sorting them by the number of inlier matches. Those are stored in the `_logs.pkl` files computed by `hloc.localize_sfm`.
