### ISSUE TITLE
problem with  3d model

### ISSUE THREAD

**Issue by slz929** [cvg/Hierarchical-Localization#131]
I try to visualize the 3d model of aachen data constructed by scripts in the repo, but i get the below? 
what's wrong?
![image](https://user-images.githubusercontent.com/17669514/146161772-65f2d046-5481-4fce-96f6-4fbaf930d950.png)

**Comment by Skydes** [comment]
That doesn't look write. You should probably visualize the keypoints and matches and look for anything abnormal.

**Comment by slz929** [comment]
> That doesn't look right. You should probably visualize the keypoints and matches and look for anything abnormal.

![image](https://user-images.githubusercontent.com/17669514/146516003-307dcfc2-b1d4-4d86-b1fc-8c4e951801c3.png)
thank you. I use the colmap GUI to visualize the matches to find them good, but the pose of images are zero like above ?
I construct the map using the sp+sg and scripts in the pipeline folder, What do you think of this problem ?
Thanks again sincerely.

**Comment by Skydes** [comment]
1. Can you make all images share the same camera model? by adding `--single_camera`
2. Anything odd in the stdout logs?

**Comment by slz929** [comment]
> 1. Can you make all images share the same camera model? by adding `--single_camera`
> 2. Anything odd in the stdout logs? 
1. i did not use the script, i can try.
2. Nope.

I use hloc/pipelines/Aachen/pipeline.py and I find it perform SFM by point_triangulator. So is it the reason that the  3d model build can not be visulized correctly?

**Comment by Skydes** [comment]
I don't understand, you mention using hloc/pipelines/Aachen/pipeline.py but show a reconstruction of RobotCar. The RobotCar pipeline is different in the way it creates the reference model from the nvm file, by reading the intrinsics from a database instead of a text file.
