### ISSUE TITLE
I have a question in reconstuction process

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#132]
I have this error. which process  has an error? Please suggest me how to solve this error. 
![Screenshot from 2021-12-15 18-07-54](https://user-images.githubusercontent.com/88375996/146176051-ad0d8780-fab3-446c-84c6-97e10494790a.png)

**Comment by Skydes** [comment]
One of the pairs does not seem to be in the matches file. Can you please address the 2 other points mentioned in https://github.com/cvg/Hierarchical-Localization/issues/28 ?

> 2. Did you make sure that the feature extraction ran smoothly beforehand?
> 3. Could you please catch the exception and print the requested key vs the keys contained in the hdf5 feature file? `hloc.utils.io.list_h5_names` might be helpful.
