### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#133]
The visualization.visualize_sfm_2d code shows the feature keypoints of only the reference images and not the query images. How can I plot the feature keypoints of the query images?
![4](https://user-images.githubusercontent.com/40207475/146541116-07ccea59-9eca-4c8f-a907-7b27fa1d3fb2.png)

**Comment by Skydes** [comment]
Use `hloc.visualization.visualize_loc` to plot matches with a query image. You can modify this code to plot the keypoints instead.
