### ISSUE TITLE
Localization algorithm 

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#134]
Does this HF-net code in the repository use RANSAC + pnp for pose estimation? 
In the localize_sfm.py file, it uses pycolmap.absolute_pose_estimation in which I didn’t find it using RANSAC. I might be wrong. Can you please clarify my doubt?

If yes, does the PnP algorithm in this case use just 3 points? But using 3 points will give it 4 solutions right? So, Shouldn’t it use 4 points for to get one single solution? 

I apologise for the confusion in advance.

**Comment by Skydes** [comment]
We use the absolute pose estimator from COLMAP, which is LO-RANSAC + P3P:
https://github.com/colmap/colmap/blob/6e10e3e2f895275298091fe991bae763891de8b9/src/estimators/pose.cc#L48
Regarding your second question, you can refer to the implementation.
