### ISSUE TITLE
About dataset collecting

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#137]
I need recommendations about dataset. if I collect different times and days in 1 datasets for reconstruction, will it affect to localization accuracy? or I should collect them in once? 
I've used different days and time dataset to build 3D model but after I've got position of query. I've plotted them in Blender,  it's not the correct position.

**Comment by Skydes** [comment]
3D reconstruction and localization can fail for different reasons, such as illumination changes, but also structural changes, symmetries (visual aliasing), degenerate motions (small baseline), or little visual overlap. Modern local features are robust to illumination changes but do not fully address the other limitations.
