### ISSUE TITLE
I got error when run reconstruction.main

### ISSUE THREAD

**Issue by pannatorn6395** [cvg/Hierarchical-Localization#141]
i try to run reconstruction.main with jupyter notebook but kernel die and also try to run reconstruction.main with python script i got    segmentation fault (core dumped).
How can i fix it ?

thank for answer sir

**Comment by Skydes** [comment]
This means that COLMAP failed and terminated. There should be some useful logging messages in the terminal window from which you launched Jupyter, can you please share this here?

**Comment by MirrorYuAI** [comment]
I also Counter the same issue

**Comment by MirrorYuAI** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [5], in <module>
----> 1 model = reconstruction.main(sfm_dir, images, sfm_pairs, features, matches, image_list=references)
      2 fig = viz_3d.init_figure()
      3 viz_3d.plot_reconstruction(fig, model, color='rgba(255,0,0,0.5)', name="mapping")

File i:\github\Hierarchical-Localization\hloc\reconstruction.py:93, in main(sfm_dir, image_dir, pairs, features, matches, camera_mode, verbose, skip_geometric_verification, min_match_score, image_list)
     91 import_images(image_dir, database, camera_mode, image_list)
     92 image_ids = get_image_ids(database)
---> 93 import_features(image_ids, database, features)
     94 import_matches(image_ids, database, pairs, matches,
     95                min_match_score, skip_geometric_verification)
     96 if not skip_geometric_verification:

File i:\github\Hierarchical-Localization\hloc\triangulation.py:60, in import_features(image_ids, database_path, features_path)
     57 db = COLMAPDatabase.connect(database_path)
     59 for image_name, image_id in tqdm(image_ids.items()):
---> 60     keypoints = hfile[image_name]['keypoints'].__array__()
     61     keypoints += 0.5  # COLMAP origin
     62     db.add_keypoints(image_id, keypoints)

File h5py\_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py\_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File D:\software\anaconda3\envs\hloc\lib\site-packages\h5py\_hl\group.py:305, in Group.__getitem__(self, name)
    303         raise ValueError("Invalid HDF5 object reference")
    304 elif isinstance(name, (bytes, str)):
--> 305     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    306 else:
    307     raise TypeError("Accessing a group is done with bytes or str, "
    308                     " not {}".format(type(name)))

File h5py\_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py\_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py\h5o.pyx:190, in h5py.h5o.open()

KeyError: 'Unable to open object (component not found)'

**Comment by Skydes** [comment]
@MirrorYuAI This error is unrelated to this issue. Does this happen with the demo data too? Can you run all notebook cells again? This issue has already been raised in https://github.com/cvg/Hierarchical-Localization/issues/28 https://github.com/cvg/Hierarchical-Localization/issues/54 https://github.com/cvg/Hierarchical-Localization/issues/10 and is generally solved by deleting the files and running again. Otherwise see the debug steps below:
> 1. Did you make sure that the feature extraction ran smoothly beforehand?
> 2. Could you please catch the exception and print the requested key vs the keys contained in the hdf5 feature file? `hloc.utils.io.list_h5_names` might be helpful.

**Comment by MirrorYuAI** [comment]
yes, this happen with the demo.ipynb, I have run the above cell smoothly again and again, at the same time, delete the outputs directory.
![Uploading image.png…]()

**Comment by MirrorYuAI** [comment]
![image](https://user-images.githubusercontent.com/18477929/151128473-7524f34d-68f1-4811-8132-1b56f0c37973.png)

**Comment by MirrorYuAI** [comment]
I Think , I Got the reason, when store the "features.h5" file, the key format is:
![image](https://user-images.githubusercontent.com/18477929/151139470-febe1fee-8a60-402d-993d-02377775b950.png)
But, when restore from "features.h5", the key format is:
![image](https://user-images.githubusercontent.com/18477929/151139664-a9f114fa-8783-4cf8-8b67-7e7442c367ea.png)

**Comment by Skydes** [comment]
Oh another Windows bug :) Can you print out the value of `references` in the notebook? Does it work if you define `references` as:
```python
references = [p.relative_to(images).as_posix() for p in (images / 'mapping/').iterdir()]
```

**Comment by MirrorYuAI** [comment]
Yes, it works, Thanks a lot!

**Comment by Skydes** [comment]
Thanks, fixed by https://github.com/cvg/Hierarchical-Localization/commit/b737255c880d4b2b23fd3e8d6d889dec1b409881. @pannatorn6395 feel free to reopen a new issue if your original problem reoccurs.
