### ISSUE TITLE
About visualization of camera pose

### ISSUE THREAD

**Issue by ZezhouCheng** [cvg/Hierarchical-Localization#143]
Hey, thanks for the wonderful codebase! 

I got confused by the visualization of camera pose [here](https://github.com/cvg/Hierarchical-Localization/blob/208c7346facb5c3004f651265ef866e0541524fe/hloc/utils/viz_3d.py#L94). Specifically, the projection from world coordinates to image pixels based on the convention of COLMAP is: 

XYZ_cam = R * XYZ_world + t; XY_im = K * XYZ_cam
Therefore, from XY_im to XYZ_world:  XYZ_world = R^T [K^(-1) * XY_im - t], and the center of the camera in world coordinate system is -R^T * t

However, based on [here](https://github.com/cvg/Hierarchical-Localization/blob/208c7346facb5c3004f651265ef866e0541524fe/hloc/utils/viz_3d.py#L94), mapping from XY_im to XYZ_world would be:  XYZ_world = R^T * K^(-1) * XY_im + t

Are there anything I missed?

**Comment by Skydes** [comment]
COLMAP indeed represents the pose from world to image as a quaternion `qvec` and a translation vector `tvec`. The function `plot_camera` however expects `R` and `t` to map image space to world space. You can see a few lines later how we call it given a `pycolmap.Image`:
https://github.com/cvg/Hierarchical-Localization/blob/208c7346facb5c3004f651265ef866e0541524fe/hloc/utils/viz_3d.py#L131-L137

`image.rotmat()` is world-to-image so `image.rotmat().T` is image-to-world. `image.projection_center()` outputs image-to-world `t`. You can see this from [the COLMAP source](https://github.com/colmap/colmap/blob/83aa3402304551eccf238bccfed81eaa3e089c70/src/base/image.cc#L146-L152). Apologies for the confusion, I will improve the documentation of `plot_camera`.

**Comment by ZezhouCheng** [comment]
Oh, I see! Thanks for the detailed reply!

**Comment by vitalii-p** [comment]
I got an error during visualization ([viz_3d.plot_reconstruction](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/viz_3d.py#L152))

'pycolmap.Image' object has no attribute 'rotmat'

Seems like they tried to get rotation matrix from the Image object. Could you suggest how to fix such issue?
