### ISSUE TITLE
Runtime Questions

### ISSUE THREAD

**Issue by lck666666** [cvg/Hierarchical-Localization#144]
![image](https://user-images.githubusercontent.com/45345893/149366949-6d724f99-ef64-4453-a866-feda27ce8d5f.png)
![image](https://user-images.githubusercontent.com/45345893/149366981-4288b0b5-490d-4c0b-b928-c7b54fbeb2a0.png)
In the paper, the runtime of  feature extraction is very short by using NV, about  the 100ms order of magnitude. However, in our experiment, the time of feature point extraction using NV seems to be particularly long for each image. 
![image](https://user-images.githubusercontent.com/45345893/149368735-cd4cef2c-c6a9-4289-b545-f19f3dcb9e04.png)

How did your team achieve the runtime in the paper?

Looking forward to your reply! Thanks sincerely.

**Comment by Skydes** [comment]
- The time reported in the paper corresponds to a single forward pass without image loading and preprocessing.
- Here you measure the total time, including file check, dataloader creation, image loading, and saving to disk.
- You need warm up cycles as the first forward pass after initialization is always slower.

**Comment by Adolfhill** [comment]
Could you please tell me how to do that?
