### ISSUE TITLE
Pixel coordinates from superpoint output

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#146]
How can I get the pixel coordinates from the keypoints or descriptors obtained from the superpoint feature extractor?

**Comment by Skydes** [comment]
You can open the resulting HDF5 file:
https://github.com/cvg/Hierarchical-Localization/blob/75fc918284be107ee37841acd58dad326919a474/hloc/localize_sfm.py#L75-L76
It should contain the keys `keypoints`, `scores`, and `descriptors` for each image.

**Comment by rishabhramteke** [comment]
Thanks but how do you get the pixel coordinates from keypoints and descriptors?
