### ISSUE TITLE
sfm_reconstruction

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#148]
I've got this problem. this error appeared before reconstruction. I think it's import images error. because I have 320 databases and 4 queries. how to make code avoid queries folder. previous version i did it in import image function but now i have no clue how to do it pls help. thanks so much
![image](https://user-images.githubusercontent.com/88375996/150355243-61a5cc04-3259-4523-a6c7-c2178c82719b.png)

**Comment by mrKornWij** [comment]
and Is it possible to visualize the map in visual studio code??

**Comment by Skydes** [comment]
You can pass a list of images to be reconstructed:
https://github.com/cvg/Hierarchical-Localization/blob/3001fcb59398296b60c54f85ca9a0529b0cd0651/hloc/reconstruction.py#L78-L81
