### ISSUE TITLE
Error in plotting keypoints for query images of robotcar

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#150]
I am getting this error :
 plot_keypoints(pred['keypoints'], colors=[0, 0, 1], ps=4)
  File "/home/ubuntu/Hierarchical-Localization/hloc/utils/viz.py", line 67, in plot_keypoints
    a.scatter(k[:, 0], k[:, 1], c=c, s=ps, linewidths=0)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

I checked the size of pred['keypoints']. Its (903,2)

**Comment by Skydes** [comment]
`plot_keypoints` expects a list of keypoint arrays, since there might be multiple images on the same row:
```python
plot_keypoints([pred['keypoints']], colors=[[0, 0, 1]], ps=4)
```

**Comment by rishabhramteke** [comment]
Thank you
