### ISSUE TITLE
What is need for using triangulation with CNN features based database?

### ISSUE THREAD

**Issue by patelajaychh** [cvg/Hierarchical-Localization#152]
As per the code, [Cambridge pipeline](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/Cambridge/pipeline.py), smf model has been triangulated from SIFT model but using CNN feature database file. 

Is there any special reason for using CNN features in this case? Why SIFT feature based reference model is not directly used?

**Comment by Skydes** [comment]
If we localize with learned local features then we need the 3D point cloud to be triangulated with the same local features. We can reuse the camera poses of the SIFT model and simply triangulate new 3D points.
