### ISSUE TITLE
3D Reconstruction shown a result like this 

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#155]
I want to know what's happened in this case. So I can solve it. Please guide.
![image](https://user-images.githubusercontent.com/88375996/152340989-75c3bf88-d6d7-45eb-b671-afc312f5d85a.png)

**Comment by wwmlhy** [comment]
Did you solve it, please? I'm also having this issue.

**Comment by mrKornWij** [comment]
> Did you solve it, please? I'm also having this issue.

I don't know either it shows up everytime. I just waited until it finished.😂
