### ISSUE TITLE
Docker image build fails because of no matching distribution for pycolmap

### ISSUE THREAD

**Issue by martinxluptak** [cvg/Hierarchical-Localization#156]
Hello,
I followed the instructions to clone the repository and build the docker image, however, upon running
`docker build -t hloc:latest .`
the installation fails with the following error:
```
#12 154.9 ERROR: Could not find a version that satisfies the requirement pycolmap (from versions: none)
#12 154.9 ERROR: No matching distribution found for pycolmap
------
executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
```

Not sure how to fix this, as running `pip install pycolmap==0.1.0` on my machine (or python venv) always resolves.
Also the following Dockerfile works:
```
FROM python:3.8-slim-buster
RUN pip3 install pycolmap==0.1.0
```

I am running WSL2 + Docker Desktop.
I saw the other closed issues regarding pycolmap installation, however, those posters were using Windows.

**Comment by Skydes** [comment]
Thanks for reporting this issue. Can you please try out PR https://github.com/cvg/Hierarchical-Localization/pull/157?
