### ISSUE TITLE
How to get experiment results?

### ISSUE THREAD

**Issue by rann1018** [cvg/Hierarchical-Localization#16]
Hi! @Skydes 
Thanks very much for all the efforts and this great repo.
I was able to re-implement all the steps of aachen dataset. However, I did not
find where I could get experiment results?  
Such as Day: 89.6 / 95.4 / 98.8 Night: 86.7 / 93.9 / 100
I checked the .pkl file and found there were only some statistics information.
What I want to do is testing new retrieve methods, so the experiment results
are important to me.
Could you tell me how can I get experiment results? Thanks a lot!

**Comment by Skydes** [comment]
The estimated query poses are written to a text file, whose path is provided to `localize_[sfm|inloc].py` [by the argument `--results`](../blob/master/hloc/localize_sfm.py#L206). It follows the format of [www.visuallocalization.net](https://www.visuallocalization.net/) and can be submitted to the evaluation server. **Please keep your evaluation entry private (untick "make visible") so as to not pollute the leaderboard.**

**Comment by rann1018** [comment]
Thanks a lot for your help!
