### ISSUE TITLE
Reconstruction issue : Do you have any way to save the model

### ISSUE THREAD

**Issue by Tarping39** [cvg/Hierarchical-Localization#168]
Hi, I've try using your code to make a 3d model on Google Colab and it's work normally for normal dataset. But when I use a dataset that more than 1,000 picture it's take too long to wait. It can finish the rest of the program but Google Colab have a limit time to use. Every day if I want a model for localize I've to run all the program again because the model isn't save like other output. therefore, do you have any way to save a model from reconstruction like other that's in the output folder? (like pairs-sfm.txt , pairs-loc.txt , matches.h5)
thank you

**Comment by ghoshaw** [comment]
Hi, do you find the method to get what you want?
