### ISSUE TITLE
How to use a model files from outputs in visualization.visualize_sfm_2d and localization

### ISSUE THREAD

**Issue by Tarping39** [cvg/Hierarchical-Localization#170]
Hi, I've use your code to make a 3d models before and it work normally. But when I start to use it with over 1,000 image in dataset. It's take very long time for reconstruction and make a model. Since I use a Google Colab notebook, I have to run the program all over again to reconstruction the model. therefore, I see that in the outputs folder there's a model file (camera.bin , images.bin , points3D.bin) which I think it's come from reconstruction process. Are there any method to use this outputs as a model variable in model = reconstruction.main(sfm_dir, images, sfm_pairs, features, matches, image_list=references) and localization?

**Comment by Skydes** [comment]
You can simply load an existing reconstruction:
```python
model = pycolmap.Reconstruction(sfm_dir)
```
and pass it to `QueryLocalizer`

**Comment by Tarping39** [comment]
Thank you very much
