### ISSUE TITLE
When will support the other standard datasets?

### ISSUE THREAD

**Issue by rann1018** [cvg/Hierarchical-Localization#18]
Hi @Skydes
Thanks for your great work on Aachen and Indoor datasets.
I notice you said you would support other datasets very soon.
I want to know exactly when the 'RobotCar Seasons' and 'CMU Seasons' datasets will be supported?
Thanks a lot.

**Comment by Skydes** [comment]
Thanks for your interest.
- Aachen v1.1 is ready to be merge and will come with some minor improvements of the process;
- RobotCar and CMU will need a little more work for the public integration. I am targeting the end of the month but can help there is an urgent need.

**Comment by rann1018** [comment]
Thanks for your quick reply.
Looking forward to your integration work.

**Comment by Skydes** [comment]
Here is a pre-release of scripts running hloc on RobotCar: https://github.com/cvg/Hierarchical-Localization/tree/robotcar/pipelines/RobotCar A clean release will happen sometime in the next weeks.
