### ISSUE TITLE
Bug in writing into COLMAP database

### ISSUE THREAD

**Issue by sontung** [cvg/Hierarchical-Localization#182]
https://github.com/cvg/Hierarchical-Localization/blob/502c600d319d3886ef3cc5f000c0b49083711441/hloc/utils/database.py#L184-L197

I found this bug when using the database generated from hloc pipelines using COLMAP code. COLMAP assumes SIFT descriptors which is uint8, but hloc might return float16 descriptors. Therefore, if using the same code (line 194) from COLMAP, we are writing only zeros into the database (float16 => uint8 = zeros). This bug is not serious if we are not using the generated database post-production (which is not my case). Sugessted changes:
line 188: `keypoints = np.asarray(keypoints, type(keypoints[0][0]))`
line 194: `descriptors = np.ascontiguousarray(descriptors, type(descriptors[0][0]))`

**Comment by Skydes** [comment]
This is not a bug - COLMAP stores descriptors as and requires them to be uint8. Yes, the database could support other datatypes, but I do not see any use case for doing so. Why should we change this? We already use hdf5 files to store keypoints and descriptors of any type.

**Comment by sontung** [comment]
Yes, it is not a major one. For a codebase that only utilizes hloc's matcher and colmap's matcher, this will require two different ways to read the descriptors and keypoints (one from the database, one from h5 files).
