### ISSUE TITLE
reference keyerror on match_features

### ISSUE THREAD

**Issue by Draconda** [cvg/Hierarchical-Localization#183]
Hi, I'm now trying to reproduce demo.ipynb in my env, with my own images,
I only set 
image_0.jpg into images / "query",
image_1.jpg into images / "mapping"
, and ran 

`references = [p.relative_to(images).as_posix() for p in (images / 'mapping/').iterdir()]
extract_features.main(feature_conf, images, image_list=[query], feature_path=features, overwrite=True)
pairs_from_exhaustive.main(loc_pairs, image_list=[query], ref_list=references)
match_features.main(matcher_conf, loc_pairs, features=features, matches=matches, overwrite=True)`

just like official implementation, but it says

`/Hierarchical-Localization/hloc/match_features.py in match_from_paths(conf, pairs_path, match_path, feature_path_q, feature_paths_refs, overwrite)
    156             # some matchers might expect an image but only use its size
    157             data['image0'] = torch.empty((1,)+tuple(grp['image_size'])[::-1])
--> 158         with h5py.File(str(feature_paths_refs[name2ref[name1]]), 'r') as fd:
    159             grp = fd[name1]
    160             for k, v in grp.items():

KeyError: 'mapping/image_1.jpg'`

how to fix this?

**Comment by Skydes** [comment]
What is the value of `query`? it should be `query/image_0.jpg`.
