### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by chuchule** [cvg/Hierarchical-Localization#184]
Hello, I'm running  pipeline.py program in Aachen now_ v1_ 1 folder  program. The IDE used is pycharm 2021.1.3 (Professional Edition), but when running, it displays "attempted relative import with no known parent package". This problem has bothered me for a long time. I sincerely hope to get your help!
![屏幕截图 2022-04-27 152036](https://user-images.githubusercontent.com/92416017/165463470-c5b2d88c-6250-4e49-a66f-ca3dfa74fdc0.jpg)

**Comment by Skydes** [comment]
Scripts need to be run from the command line as `python -m hloc.pipelines.Aachen_v1_1.pipeline`. I don't know if this is possible with PyCharm.

**Comment by chuchule** [comment]
OK, thank you very much for your reply. I wish you every success in your work!
