### ISSUE TITLE
Function function

### ISSUE THREAD

**Issue by chuchule** [cvg/Hierarchical-Localization#188]
Hi！I'm watching a movie called triangulation Py file. One of the functions makes me very confused. I really hope you can tell me the function of this function. Thank you very much!
![屏幕截图 2022-05-08 165750](https://user-images.githubusercontent.com/92416017/167289119-ea3510ca-5655-4ece-9eb8-5568581e6379.jpg)

**Comment by Skydes** [comment]
This is [a COLMAP reconstruction object](https://github.com/colmap/pycolmap#reconstruction-object) with images, cameras, and 3D points.
