### ISSUE TITLE
Can't instantiate abstract class SuperGlue with abstract methods _forward, _init

### ISSUE THREAD

**Issue by hiXiaoYU** [cvg/Hierarchical-Localization#189]
Can't instantiate abstract class SuperGlue with abstract methods _forward, _init

**Comment by hiXiaoYU** [comment]
![2022-05-15 10-49-52 的屏幕截图](https://user-images.githubusercontent.com/105405735/168455068-3de84797-d3ec-4ba6-b54f-2545cd9f86a5.png)

**Comment by Skydes** [comment]
What version of Python are you using?

**Comment by hiXiaoYU** [comment]
python3.7.13 .I've solved the problem by downloaded the superclue module and added it to the path.Now I have encountered an error mentioned in the previous question and tried to print the error you said, but I don't know how to correct i
![2022-05-16 12-27-01 的屏幕截图](https://user-images.githubusercontent.com/105405735/168520403-471dac9a-44d8-4af4-bb76-e2341c3387e1.png)
![2022-05-16 12-27-05 的屏幕截图](https://user-images.githubusercontent.com/105405735/168520416-45572732-c3e2-484a-9d26-c395e8603762.png)
t

**Comment by Skydes** [comment]
You can try to delete the matches hdf5 file and run the matching again.

**Comment by hiXiaoYU** [comment]
Sorry to bother you again, I have a question about the lis . I printed the data of fd and name0
![Uploading 截图_2022-05-23_13-58-25.png…]()
![Uploading 截图_2022-05-23_13-58-52.png…]()

t

**Comment by hiXiaoYU** [comment]
I am sorry for bother you again . It is no useful about deleting the matches hdf5 file .  What is the name of this file? feats-superpoint-n4096-r1024.h5  ? i meet the same issue about the picture again . thanks

**Comment by hiXiaoYU** [comment]
![3](https://user-images.githubusercontent.com/105405735/172581771-04ebcafd-2510-4818-bba4-b5bfbe5cc967.png)
