### ISSUE TITLE
Missing Images in InLoc Dataset

### ISSUE THREAD

**Issue by half-potato** [cvg/Hierarchical-Localization#19]
Within the `pairs-query-netvlad40.txt`, the file `DUC_cutout_113_240_0.jpg` is mentioned as being part of a pair. However, I downloaded the InLoc dataset with the following commands:
```
git clone https://github.com/HajimeTaira/InLoc_dataset
cd InLoc_dataset
./extract_db_all_mirror.sh
./extract_query_mirror.sh
```
And it does not contain this file. 
I have attached a comprehensive list of the files downloaded.
[downloaded_files.txt](https://github.com/cvg/Hierarchical-Localization/files/5211908/downloaded_files.txt)

**Comment by Skydes** [comment]
After some investigation is seems that the mirror file for DUC2 `https://www.dropbox.com/s/t2izj3dkzk81jg4/DUC2.tar.bz2?dl=1` has an issue. Uncompressing it with `tar -jtvf DUC2.tar.bz2` gives:
```
bzip2: Data integrity error when decompressing.
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
This results in 711 cutout images missing compared to the original dataset, including `DUC_cutout_113_240_0.jpg`. Tagging @HajimeTaira who may be able to help here.

@half-potato in the meantime could you try downloading with `extract_db_all.sh` ?

**Comment by HajimeTaira** [comment]
Thank you for sharing the issue. I reproduced the problem and found something happens when downloading from Dropbox. The original bzip2 file uploaded to the server (and still being synced) actually includes `DUC_cutout_113_240_0.jpg` but downloaded file somehow loses the image. One potential reason would be that `wget` seems once to be terminated by the server, after one hour has passed. I'm now uploading the original file to Dropbox server again. If it won't solve the problem, I'll try to divide the file into two or more separated file so one can download the whole file without termination.

**Comment by Skydes** [comment]
Awesome, thanks for the timely reply!

**Comment by HajimeTaira** [comment]
I've succeeded to construct full DUC2 image set from [two separated tar.gz files](https://github.com/HajimeTaira/InLoc_dataset/blob/91f0c0d780184bc86de275534928d0360b8d939c/extract_db_all_mirror.sh#L9-L15). These files cause no problem while downloading, whereas re-uploaded original file still corrupts. So could you try to download the database images again, using the lines above?
I'll merge these changes to master soon, after dividing other large floors into separated files.

**Comment by half-potato** [comment]
This download link works: http://www.ok.sc.e.titech.ac.jp/INLOC/materials/cutouts/DUC2.tar.bz2

**Comment by HajimeTaira** [comment]
@half-potato Good to hear that the original link works for you. For more speedy and stable downloading from dropbox, I also prepared several sub-files for large floors. https://github.com/HajimeTaira/InLoc_dataset/pull/6

Thank you again for sharing the issue and sorry for the inconvenience.

**Comment by Skydes** [comment]
Thanks @HajimeTaira for fixing this. Closing this issue then.
