### ISSUE TITLE
Pycolmap need

### ISSUE THREAD

**Issue by zr19980402** [cvg/Hierarchical-Localization#191]
Why we need the pycolmap >= 0.2.0? but it cannot install at WINDOWS

**Comment by Skydes** [comment]
For Windows pycolmap needs to be installed from source: https://github.com/colmap/pycolmap#windows We provide pre-built binaries for linux and macOS only.

**Comment by zr19980402** [comment]
I did it by the building steps. but still cannot success.  the error is [https://github.com/colmap/pycolmap/issues/70](url)
