### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by hiXiaoYU** [cvg/Hierarchical-Localization#192]
Sorry to bother you again, I have a question about the list . I printed the data of fd and name0
![截图_2022-05-23_13-58-25](https://user-images.githubusercontent.com/105405735/169753376-886206c0-d0d5-4078-9a8b-997cb39a68f1.png)
![截图_2022-05-23_13-58-52](https://user-images.githubusercontent.com/105405735/169753381-12fbbd86-932a-4dc5-9734-c8b2b49eedd0.png)
.

**Comment by Skydes** [comment]
I will not be able to help without more details.
