### ISSUE TITLE
Question about the 3D LiDAR model

### ISSUE THREAD

**Issue by Gatsby23** [cvg/Hierarchical-Localization#195]
Dear doctor:
        Thank you for your wonderful work about the hloc. It really helps us in visual localization or loop closure detection. But there are few questions about the 3D model, as you have mentioned in the README.md.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/18000675/170256375-22767380-2590-4788-8f86-7e8bef6ebe98.png">
When the LiDAR scan points are available, the step 2 can be skipped. However, the LiDAR points cloud is the different modal data from visual data. Why we can use the LiDAR scanner as the 3D model. More precisely, how to find the covisible visual data with the LiDAR 3D model？ I really need for your help.

Yours
Qi Wu

**Comment by Skydes** [comment]
A Lidar 3D point cloud can be used to lift 2D points in reference images to 3D. This is possible by rendering a depth map for each reference image, through splatting or meshing.
