### ISSUE TITLE
How are the dependencies resolved? / Where is colmap?

### ISSUE THREAD

**Issue by reynoldscem** [cvg/Hierarchical-Localization#196]
I am quite confused about how the requirement of installing colmap has been avoided? I am trying to use this library with a small change to the colmap source, but I can't seem to find where it is / how hloc installs it.

If I build colmap and pycolmap locally, hloc doesn't seem to use them. Could someone advise on how it is installed / packaged? And how we can forcibly use a local version instead?

**Comment by Skydes** [comment]
1. Uninstall all binaries of COLMAP and pycolmap (`pip uninstall pycolmap`)
2. Build and install COLMAP from source
3. Build pycolmap from source: https://github.com/colmap/pycolmap#building-from-source

**Comment by zr19980402** [comment]
I have another question I cannot build Pycolmap by its steps in Windows. @ #[https://github.com/colmap/pycolmap/issues/70](url)

**Comment by zr19980402** [comment]
If it's coused by the source webs(https://pypi.tuna.tsinghua.edu.cn/simple), could you tell me the right way to build the pycolmap. I have stuck in it for several days. So sad
