### ISSUE TITLE
RobotCar dataset triangulation fail.

### ISSUE THREAD

**Issue by sijin-dm** [cvg/Hierarchical-Localization#20]
Hi @Skydes,

When I try to use RobotCar dataset by modifying the pipeline as you did in pipeline_Aachen.ipynb, in the step of `triangulation.main`, I get following error from colmap:

```
Triangulating image #25989 (20861)
==============================================================================

  => Image sees 0 / 453 points
  => Triangulated 0 points

==============================================================================
Retriangulation
==============================================================================

  => Merged observations: 0
  => Completed observations: 0

==============================================================================
Bundle adjustment
==============================================================================

F0916 10:15:07.367084 25425 colmap.cc:1573] Check failed: bundle_adjuster.Solve(&reconstruction) 
*** Check failure stack trace: ***
    @     0x7f0ec3ba10cd  google::LogMessage::Fail()
    @     0x7f0ec3ba2f33  google::LogMessage::SendToLog()
    @     0x7f0ec3ba0c28  google::LogMessage::Flush()
    @     0x7f0ec3ba3999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55b97c6a788d  (unknown)
    @     0x55b97c695a0e  (unknown)
    @     0x7f0ebf823b97  __libc_start_main
    @     0x55b97c69f6aa  (unknown)
[09/16/2020 10:15:07 WARNING] Problem with point_triangulator, exiting.
```
It seems that the overlap is not enough to triangulate.  Have you meet the same problem before?
And I am really curious about how to reproduce the result of `Hierarchical Localization - SuperPoint + SuperGlue` at https://www.visuallocalization.net/benchmark/ for RobotCar Seasons dataset.

**Comment by Skydes** [comment]
I will very soon release an update than supports RobotCar. The way you are selecting SfM image pairs is maybe incorrect - if you used covisibility, your initial model might not be correct.

**Comment by Skydes** [comment]
Here is a pre-release of scripts running hloc on RobotCar: https://github.com/cvg/Hierarchical-Localization/tree/robotcar/pipelines/RobotCar A clean release will happen sometime in the next weeks.

**Comment by Sijin0309** [comment]
> Here is a pre-release of scripts running hloc on RobotCar: https://github.com/cvg/Hierarchical-Localization/tree/robotcar/pipelines/RobotCar A clean release will happen sometime in the next weeks.

That's great! Thanks for your kind release, I will take a shot.

**Comment by sijin-dm** [comment]
Sorry for the late reply. I have try the new RobotCar pipeline, it works well! Could you explain more detail about your idea using multi-camera for localization?
