### ISSUE TITLE
How to generate input data that I don't have？

### ISSUE THREAD

**Issue by fumenglin** [cvg/Hierarchical-Localization#212]
Hi：
    I want to use inLoc for indoor positioning, I only have indoor pictures, no 3D points converted (cse_scan_000.ptx.mat), transformation matrix that converts 3D points in original ptx file to global coordinates (cse_scan_000.ptx.mat) and the scan points (XYZcut) (cse_cutout_000_0_-30.jpg.mat), 

how do I generate the above data?

Not running the demo,  processing it with my own data

thank you very much.

**Comment by Skydes** [comment]
The 3D scans are required. You are free to open an issues on the [InLoc repository](https://github.com/HajimeTaira/InLoc_dataset) or reach out to the authors of the dataset. There are also alternative download links here: https://github.com/HajimeTaira/InLoc_dataset/blob/b9a4ee2668c9d2ffe76f83613b2afba26d6fabb8/extract_db_all_mirror.sh#L52-L71
