### ISSUE TITLE
unable to find GPS matcher

### ISSUE THREAD

**Issue by sumanttyagi** [cvg/Hierarchical-Localization#214]
Hi ,
i want to run this script https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3 on the images which i have.
what i have understood is i need to install colmap,pycolmap then install pixsfm and hloc.After that i run this script directly on the env to get the output however i am getting below error 
![image](https://user-images.githubusercontent.com/63983323/184112537-e8db9e24-d711-443d-8937-5c8923c1c691.png)

Kindly tell me if i am doing anything wrong in installation or it has to be other way round ?

thanks

**Comment by Skydes** [comment]
hloc has no module `pairs_from_gps`. This gist likely needs a fork that is private. You would need to reach out to the author.

**Comment by Skydes** [comment]
It looks like the GPS matcher is here: https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0

**Comment by sumanttyagi** [comment]
sorry i am kind of new to this. How can run this ?
should i be using it as a function then run it ?

**Comment by MACILLAS** [comment]
Updated the GIST from hturki added support for Skydio and updated DJI implementation... Hope this helps someone! :)
 
https://gist.github.com/MACILLAS/03f067676a2ce44315d3a55abc0db4d2
