### ISSUE TITLE
Visualization (plotly probably) issue

### ISSUE THREAD

**Issue by ducha-aiki** [cvg/Hierarchical-Localization#215]
Hi, 

I am experiencing weird bug: when moving/paning/etc reconstruction, as in demo, start position is OK:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/4803565/185109033-34831739-6033-47a8-8b31-f3386c878810.png">

However, once I start zooming, it does not delete older version, and I end up with multiple versions of the reconstruction, e.g. as in here you can see 4 versions of zoom :

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/4803565/185109709-c6d0d3f4-02df-4b77-9a28-fad6705e5dbf.png">

***
Any  idea how to fix that? Updating plotly does not help.

**Comment by Skydes** [comment]
Not sure not understand what you are showing here; is it just the results of the following?
```python
fig = init_figure()
plot_cameras(fig, rec1)
plot_cameras(fig, rec2)
```
The implementation of `plot_camera` is frankly suboptimal so this is maybe due to plotly blowing up. What happens if you simplify the visualizations by commenting out the following?
https://github.com/cvg/Hierarchical-Localization/blob/e12b4bf2016a174ff2e5dd8a91063f9d00df91f6/hloc/utils/viz_3d.py#L102-L121

**Comment by ducha-aiki** [comment]
No, it is is a result of:

```python3
from hloc.utils.viz_3d import init_figure, plot_points, plot_reconstruction, plot_camera_colmap
fig3d = init_figure()
plot_reconstruction(fig3d, rec)
fig3d.show()
```

And then using mouse controls to see reconstruction from different points.

Anyway, commenting out the lines helped, thank you!

**Comment by ducha-aiki** [comment]
Actually, I was wrong - it helped for a while, then I have the same problem.

**Comment by Skydes** [comment]
This is probably the same problem - plotly cannot handle a large number of 3D elements. It is sufficient for small scenes but not for the one that you show here. Here is an alternative viewer based on Open3D: https://gist.github.com/Skydes/892ede47621fe4b2a0aea6bfd8f375d2 Let me know if this works for you.
