### ISSUE TITLE
Multiple cameras instead of single one

### ISSUE THREAD

**Issue by alex-klimov** [cvg/Hierarchical-Localization#219]
Brilliant library! Thank you for creating it.

I have an issue in following setup. I have multiple videos captured with single iPhone. Videos are converted to images with ffmpeg tool. All images are getting localized in 3D reconstruction and the position seems to be correct. However, in output colmap model I see mutiple cameras created with different intrinsic parameters.

I tried to specify mode with Single camera, but that didn't change anything:
```python
model = reconstruction.main(sfm_dir, images, sfm_pairs, feature_path, match_path, camera_mode=pycolmap.CameraMode.SINGLE, verbose=True)
```

How should I specify that I have single camera only? If I know intrinsic parameters, can I pass them over?

**Comment by Skydes** [comment]
1) Multiple cameras: does it create a different camera per video or per image? do the resulting cameras differ in terms of image width, height, or other parameters? The default mode, auto, should already assign a single camera to multiple images if they share the same width, height, and EXIF (see [here](https://github.com/colmap/colmap/blob/d6f528ab59fd653966e857f8d0c2203212563631/src/exe/feature.h#L54-L60)).

2) Providing intrinsic parameters: check out PR https://github.com/cvg/Hierarchical-Localization/pull/210, in which `image_options` accepts:
- camera_model: name of the camera model, defined [here](https://github.com/colmap/colmap/blob/master/src/base/camera_models.h)
- camera_params: comma-separated list of parameters
 
Example:
```python
opts = dict(camera_model='SIMPLE_RADIAL', camera_params=','.join(map(str, (f, cx, cy, k))))
model = reconstruction.main(..., image_options=opts)
```

You can decide to not refine them by adding
```python
reconstruction.main(..., mapper_options=dict(ba_refine_focal_length=False, ba_refine_extra_params=False))
```

**Comment by alex-klimov** [comment]
> 1. Multiple cameras: does it create a different camera per video or per image? do the resulting cameras differ in terms of image width, height, or other parameters? 

For 222 images I get 222 cameras in colmap model. They all have the same type, resolution, but other parameters are different. A few lines from exported `cameras.txt` are below. The same result was with AUTO mode.
```
222 SIMPLE_RADIAL 1920 1080 1817.3906929107477 960 540 0.019831876407632894
221 SIMPLE_RADIAL 1920 1080 1821.8578476946591 960 540 0.016013266424875335
220 SIMPLE_RADIAL 1920 1080 1811.8596737213134 960 540 0.02046293865115948
219 SIMPLE_RADIAL 1920 1080 1790.8546264657789 960 540 0.049830436594508185
```
Please note, that all these images come from the same iPhone camera. There is an extra step of filming the video first and then using ffmpeg to screenshot frames.

Is this result expected?

> 2. Providing intrinsic parameters: check out PR

Thank you! Looking...

**Comment by alex-klimov** [comment]
It works, I needed to grab the latest version and recompile `pycolmap`.

This code:
```python
opts = dict(camera_model='OPENCV')
model = reconstruction.main(sfm_dir, images, sfm_pairs, feature_path, 
                            match_path, camera_mode=pycolmap.CameraMode.SINGLE,
                            image_options=opts,
                            verbose=True)
```
now returns this, which is exactly what I need. Thank you!
```
# Camera list with one line of data per camera:
#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 1
1 OPENCV 1920 1080 1811.1298157393007 1810.6222237771328 960 540 0.11586891523566556 -0.2866863386323682 0.0007904899863632694 -0.00084223979478173624
```
