### ISSUE TITLE
New Images

### ISSUE THREAD

**Issue by PKehnel** [cvg/Hierarchical-Localization#22]
Hey,
thanks a lot for the amazing toolbox. 
I got the project working on a custom dataset, now my goal would be to use this model and the matches / feature files to localize an new image, that was not part of the original dataset. 

Any ideas how to approach this, obviously I get an Object missing error, when just using the previous matches /feature files. 
Hope this is not out of scope.

**Comment by Skydes** [comment]
Sure, here is how I would do it:
- Run `extract_features` on the folder of query images, pointing to the same feature file as the reference images;
- Generate a list of localization pairs between each query and one or several references images - e.g. using [image retrieval](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pairs_from_retrieval.py) with [DIR](https://github.com/almazan/deep-image-retrieval), [prior poses](https://github.com/cvg/Hierarchical-Localization/blob/dev/hloc/pairs_from_poses.py) from local SLAM tracking or GPS, or any other mean;
- Run `match_features` using this list of pairs, pointing to the same match file as the reference images;
- Run `localize_sfm`

**Comment by PKehnel** [comment]
Thanks for the advice, this seems to be similar to  your approach from the dev branch for 4Seasons.
Will try it out! 
Goal is to run it in real time in a private ar application. Lets see.

**Comment by PKehnel** [comment]
Loc pairs: 
Since DIR on a custom dataset is not really possible for me ([Issue:](https://github.com/naver/deep-image-retrieval/issues/22) Unfortunately, You need to implement multi-staged backpropagation in your self.) 

Would it also be possible to generate the localization pairs for the query and some references image, via similarity in the feature files?  Using the descriptors and the scores in a simplified way and storing everything in a Annoy or some other similarity search database?

**Comment by Skydes** [comment]
DIR provides pretrained models that should generalize well to multiple environments - retraining should not be needed. Alternatively, you could indeed perform image retrieval with local features using something like BoW. ASL-Feat [has an example](https://github.com/lzx551402/aslfeat#4-benchmark-on-oxford-buildings-dataset-for-image-retrieval).
