### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#220]
is there another way to visualize 3D point cloud map ? no colmap gui

**Comment by Skydes** [comment]
- for small point clouds, in a notebook with plotly: [`hloc/utils/viz_3d`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/viz_3d.py), example usage in the demo notebook
- for larger point clouds, standalone script with Open3D: https://gist.github.com/Skydes/892ede47621fe4b2a0aea6bfd8f375d2

**Comment by mrKornWij** [comment]
could open3D visualize the localization part?

**Comment by mrKornWij** [comment]
Using open3d and it shown an error 'segmentation fault (coredump)'. I guess it happen in o3d visualize line
