### ISSUE TITLE
6dof

### ISSUE THREAD

**Issue by RoyalLii** [cvg/Hierarchical-Localization#221]
The output 6dof contains 7 floating point numbers, what do they mean?

**Comment by Skydes** [comment]
As per the documentation of https://www.visuallocalization.net/datasets/
> For each query image for which your method has estimated a pose, use a single line. This line should store the
result as `name.jpg qw qx qy qz tx ty tz`.  Here,  `name` corresponds to the filename of the image, without any directory names. `qw qx qy qz` represents the **rotation** from world to camera coordinates as a 
**unit quaternion**. `tx ty tz` is the camera **translation** (**not the camera position**).

**Comment by RoyalLii** [comment]
Thank you so much!
How to get the pycolmap.Reconstruction type from the saved path for the sfm model reconstructed with pycolmap.incremental_mapping？

**Comment by RoyalLii** [comment]
Hi, Is tx ty tz the translation of the camera with respect to the world coordinate ?

**Comment by Skydes** [comment]
translation = position of the world origin in camera coordinates.
