### ISSUE TITLE
Reconstructing 3D map with known camera poses

### ISSUE THREAD

**Issue by thealchemist89** [cvg/Hierarchical-Localization#222]
Hi,

I have a set of mapping data and their corresponding camera 6-DoF poses. I understand from the sample file that I could use reconstruction.main() to triangulate the points and create a 3D map.

However, doing so would mean I am not fully utilizing the information I have on the map. How do I ingest these known camera poses into the reconstruction process?

Thank you for your patience and guidance!

Kenny

**Comment by Skydes** [comment]
1. Create an empty reconstruction with pycolmap: add images and cameras but no 3D points
```python
rec = pycolmap.Reconstruction()
camera_id = 1
cam1 = pycolmap.Camera(model_name, w, h, params, camera_id)
rec.add_camera(cam1)
im1 = pycolmap.Image(image_name, [], tvec, qvec, camera_id, id=1)
rec.add_image(im1)
rec.write("path/")
```
2. Save it to disk
3. Run `hloc.triangulation` instead of `hloc.reconstruction`

**Comment by thealchemist89** [comment]
Thank you @Skydes - that helps!

**Comment by mrKornWij** [comment]
> 1. Create an empty reconstruction with pycolmap: add images and cameras but no 3D points
> 
> 
> ```python
> rec = pycolmap.Reconstruction()
> camera_id = 1
> cam1 = pycolmap.Camera(model_name, w, h, params, camera_id)
> rec.add_camera(cam1)
> im1 = pycolmap.Image(image_name, [], tvec, qvec, camera_id, id=1)
> rec.add_image(im1)
> rec.write("path/")
> ```
> 
>     2. Save it to disk
> 
>     3. Run `hloc.triangulation` instead of `hloc.reconstruction`
@Skydes 
Before using this guide  I should extract feature of all known pose image first right?

**Comment by gtangg12** [comment]
You should also rec.register_image(id) if you want rec.write to work properly i.e. write the image to the path
