### ISSUE TITLE
Question about running time

### ISSUE THREAD

**Issue by salt0107fish** [cvg/Hierarchical-Localization#224]
Hi! Thanks for your work~
When I run pipline.py for Aachen_v1.1, I found it would take too much time. I used a single RTX3060 GPU. The running details are as follows:
`[2022/08/23 17:12:39 hloc INFO] Found 133066 pairs.
[2022/08/23 17:12:40 hloc INFO] Matching local features with configuration:
{'model': {'name': 'superglue',
           'sinkhorn_iterations': 50,
           'weights': 'outdoor'},
 'output': 'matches-superglue'}
Loaded SuperGlue model ("outdoor" weights)
  0%|          | 181/88952 [01:35<13:01:42,  1.89it/s]`
Is that reasonable? If not, what's the normal speed?
Thank you~

**Comment by ThomasParistech** [comment]
It might be related to a similar issue I posted on pixsfm about loading of SuperGlue weights being slow (Eventhough it wasn't that slow!)
https://github.com/cvg/pixel-perfect-sfm/issues/69

**Comment by ThomasParistech** [comment]
When calling  match_features.main, the number of iterations required to load SuperGlue model seems to be exactly proportional to the number of images to match against the database.

When matching one image against the database
```
Loaded SuperGlue model ("outdoor" weights)
 42%|████   | 72/173 [00:02<00:03, 31.96it/s]
```
 
When matching 4 images against the database
```
 Loaded SuperGlue model ("outdoor" weights)
 34%|████| 237/692 [00:07<00:14, 31.41it/s]
```

692=173*4

I don't quite understand why isn't this number a constant :thinking:

**Comment by Skydes** [comment]
@ThomasParistech This progress bar tracks the matching process itself, not the loading of the model... The number of iterations if the number of pairs to be matched.
https://github.com/cvg/Hierarchical-Localization/blob/4961d117b4290e97b03120c54694224a823e7e04/hloc/match_features.py#L150

@salt0107fish I generally reach 10-20 it/s with a 2080 Ti when loading features from an SSD - this can drop if your disk is much slower. Parallel loading of features (PR https://github.com/cvg/Hierarchical-Localization/pull/162) might help but I do not plan to support this soon.

**Comment by silver-obelisk** [comment]
> 此进度条跟踪匹配过程本身，而不是模型的加载...迭代次数是要匹配的对数。
> 
> https://github.com/cvg/Hierarchical-Localization/blob/4961d117b4290e97b03120c54694224a823e7e04/hloc/match_features.py#L150
> 
> 从 SSD 加载功能时，我通常会使用 10 Ti 达到 20-2080 it/s - 如果您的磁盘速度慢得多，这可能会下降。并行加载功能（PR #162）可能会有所帮助，但我不打算很快支持此功能。

I foud in the paper superglue will spend less time comapred with sift+nn,but in my test superpoint+superglue in sfm is too slow  compared with colmap, I used exhaustive matching  for both,colmap only spend hundred seconds but superpoint+superglue used about 15 min.I wondered why?  I used 3070 in my test.
