### ISSUE TITLE
ModuleNotFoundError: No module named 'SuperGluePretrainedNetwork.models'

### ISSUE THREAD

**Issue by houyongdi** [cvg/Hierarchical-Localization#228]
Hi!
When I was running pipeline_SfM.ipynb, I got an error:
ModuleNotFoundError: No module named 'SuperGluePretrainedNetwork.models'
![Screenshot 2022-09-01 10:39:53](https://user-images.githubusercontent.com/80138814/187821189-75ecb53b-bd5c-44ae-8fad-9b06df938e89.png)

Can you help me? @Skydes

**Comment by houyongdi** [comment]
> Hi! When I was running pipeline_SfM.ipynb, I got an error: ModuleNotFoundError: No module named 'SuperGluePretrainedNetwork.models' ![Screenshot 2022-09-01 10:39:53](https://user-images.githubusercontent.com/80138814/187821189-75ecb53b-bd5c-44ae-8fad-9b06df938e89.png)
> 
> Can you help me? @Skydes

**Comment by houyongdi** [comment]
I solved it,
thanks!

**Comment by GerasimovIV** [comment]
Can you explain how? @houyongdi

**Comment by GerasimovIV** [comment]
Oh, As I see, there is another repo with it ... ok

https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/superglue.py

**Comment by feiyangsuo** [comment]
> > Oh, As I see, there is another repo with it ... ok
> > https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/superglue.py
> 
> Hello, could you tell me how you solved it? This question has been bothering me all day.

try pulling this repository [https://github.com/magicleap/SuperGluePretrainedNetwork](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/superglue.py) into third_party/SuperGluePretrainedNetwork (works for me)

**Comment by clousy188** [comment]
AttributeError: 'numpy.ndarray' object has no attribute 'replace'
![image](https://github.com/cvg/Hierarchical-Localization/assets/130050060/2446bc55-5323-492b-b152-4b8b4522cb13)
