### ISSUE TITLE
SFM / docker / performance .. slow

### ISSUE THREAD

**Issue by kayjean** [cvg/Hierarchical-Localization#23]
Hi! Sorry to disturb you.
When I try to evaluate sfm function ( pipeline_SfM.py with docker ), the performance is slow

I had installed nvidia and cuda 10.1 driver. but it takes 29 hours to load SuperGlue model $%@#
![Screenshot from 2020-10-20 16-15-34](https://user-images.githubusercontent.com/17929973/96561442-2a89ed80-12f2-11eb-8692-3def48b5adcb.png)

Could you tell me how I can speed up the sfm? Thanks!

**Comment by Skydes** [comment]
The model loaded correctly, it is actually the matching that takes 29 hours. 13.46 s per iteration does not sound right, the inference probably runs on CPU. Can you check that your PyTorch install as CUDA available?

**Comment by kayjean** [comment]
YA!! I try to upgrade the docker with nvidia support. CPU 29hours to GPU 59minutes. Cool

Thanks!

By the way. What is the normal and average value?


![Screenshot from 2020-10-20 18-11-15](https://user-images.githubusercontent.com/17929973/96572756-cf5ef780-12ff-11eb-8325-35686bfa34dc.png)

**Comment by Skydes** [comment]
Great! The maximum speed depends on your GPU and number of keypoints, but 2 to 5 iterations per sec sounds reasonable.

**Comment by silver-obelisk** [comment]
> 伟大！最大速度取决于您的 GPU 和关键点数量，但每秒 2 到 5 次迭代听起来很合理。

I wonder why it so slow compared with colmap? using colmap to do sfm only spend 5-10 mins
