### ISSUE TITLE
Visualizing the model via prior poses rotates poses

### ISSUE THREAD

**Issue by famfa693** [cvg/Hierarchical-Localization#230]
Hi, Thanks for your amazing work!

I generated an empty model using prior poses and triangulated the points to construct the SFM model. The issue is that when I plot the camera poses of reconstructed model via scatter plot, the correct trajectory is shown. However, when I use "viz_3d.plot_reconstruction" or "viz_3d.plot_camera_colmap" functions the trajectory is no longer shown correctly. I have there questions here: 

1. Will this effect on the localization results?
2. How can I plot the correct trajectory of the model?
3. Do I need to rotate the ground truth poses before generating the SFM model?

Thanks so much in advance for your help!

<img width="466" alt="Screen Shot 2022-09-12 at 11 55 25 AM" src="https://user-images.githubusercontent.com/109170015/189735511-69a55456-06dd-47b6-ac00-c6b8382f784f.png">
<img width="453" alt="Screen Shot 2022-09-12 at 11 56 55 AM" src="https://user-images.githubusercontent.com/109170015/189735540-186657ca-1b9a-4052-aa56-8e3094f3ba9e.png">

**Comment by Skydes** [comment]
In COLMAP models, camera poses are expected to transform from world to camera coordinates. You likely assumed the opposite. This will yield an incorrect 3D model.

**Comment by famfa693** [comment]
Thanks! That resolved the issue.
