### ISSUE TITLE
Could you recommend me please. How can i scale hloc map with real world scale

### ISSUE THREAD

**Issue by pannatorn6395** [cvg/Hierarchical-Localization#237]

**Comment by pannatorn6395** [comment]
Hi, 
Now i can know pose of query [qw, qx, qy, qz, tx, ty, tz] but i don't know how to scale with real world coordinate or can i assign initial pose for hloc map 
Thank you for your patience and guidance! 
Kenny

**Comment by RoyalLii** [comment]
Hi, have you solved it yet.How do I get [qw,qx,qy,qz,tx,ty,tz] to correspond to real world coordinates

**Comment by Skydes** [comment]
SfM cannot estimate the metric scale of the reconstruction from images only. If you have GPS measurements (e.g. extracted form EXIF tags), you can scale the model: https://colmap.github.io/faq.html#geo-registration
