### ISSUE TITLE
Which model should I train for applying the hloc on custom dataset?

### ISSUE THREAD

**Issue by YanAwithU** [cvg/Hierarchical-Localization#238]
Hi !
Thanks for your works!
I want to implement this repo on my own dataset.
I'll use superpoint, superglue, netvlad, then which model should I train for applying the hloc on custom dataset?
As I know, above models are all pretrained network, thus I think I should train some models(or not).

**Comment by Skydes** [comment]
If you have regular indoor and outdoor data, using the pretrained models should be fine and you should not need to retrain any of them.
