### ISSUE TITLE
Using Adalam Matcher

### ISSUE THREAD

**Issue by reynoldscem** [cvg/Hierarchical-Localization#239]
Recently the Adalam matcher was merged, but I don't seem to be able to use it. Does it only work for certain types of features? If so, which?

I am running off the current head at the time of writing which is `972b57fe695c4e3b3634c9140acec58060de7ecc`.

The error I receive, during `reconstruction.main` is:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In [12], line 1
----> 1 model = reconstruction.main(sfm_dir, images, sfm_pairs, feature_path, match_path)

File ~/Hierarchical-Localization/hloc/reconstruction.py:118, in main(sfm_dir, image_dir, pairs, features, matches, camera_mode, verbose, skip_geometric_verification, min_match_score, image_list, image_options, mapper_options)
    116 image_ids = get_image_ids(database)
    117 import_features(image_ids, database, features)
--> 118 import_matches(image_ids, database, pairs, matches,
    119                min_match_score, skip_geometric_verification)
    120 if not skip_geometric_verification:
    121     estimation_and_geometric_verification(database, pairs, verbose)

File ~/Hierarchical-Localization/hloc/triangulation.py:93, in import_matches(image_ids, database_path, pairs_path, matches_path, min_match_score, skip_geometric_verification)
     91 if min_match_score:
     92     matches = matches[scores > min_match_score]
---> 93 db.add_matches(id0, id1, matches)
     94 matched |= {(id0, id1), (id1, id0)}
     96 if skip_geometric_verification:

File ~/Hierarchical-Localization/hloc/utils/database.py:200, in COLMAPDatabase.add_matches(self, image_id1, image_id2, matches)
    199 def add_matches(self, image_id1, image_id2, matches):
--> 200     assert(len(matches.shape) == 2)
    201     assert(matches.shape[1] == 2)
    203     if image_id1 > image_id2:

AssertionError: 
```

**Comment by Skydes** [comment]
AdamLAM is compatible only with features based on DoG, which has per-point orientation and scale, so `sift` or `sosnet` in `hloc.extract_features`. When trying to use it with other features (e.g. SuperPoint), it should fail at
https://github.com/cvg/Hierarchical-Localization/blob/972b57fe695c4e3b3634c9140acec58060de7ecc/hloc/matchers/adalam.py#L45

**Comment by reynoldscem** [comment]
@Skydes Thanks for the reply. It doesn't seem to be this.  The same error appears to happen with both `sosnet` and `sift`.

I'm just working off the `pipeline_SfM` notebook, with the only change being swapping the feature and matcher confs.

**Comment by reynoldscem** [comment]
I think it may be crashing while trying to add empty matches to the database?

**Comment by reynoldscem** [comment]
Might just be putting a plaster on a deeper problem, but this appears to fix it:

https://github.com/cvg/Hierarchical-Localization/pull/240

**Comment by Skydes** [comment]
This is an unrelated error, try to run the whole process from scratch on a empty directory.
