### ISSUE TITLE
Ignore image regions with a mask

### ISSUE THREAD

**Issue by alex-klimov** [cvg/Hierarchical-Localization#251]
Colmap allows to ignore regions of the image for a feature extraction by providing a mask:
https://colmap.github.io/faq.html#mask-image-regions

Does HLoc support similar functionality? I need that to ignore dynamic object in otherwise static scene.

**Comment by Skydes** [comment]
There is already a PR for it: https://github.com/cvg/Hierarchical-Localization/pull/190 It is outdated and I do not plan to merge it but it is straightforward to add.

**Comment by alex-klimov** [comment]
Thank you! I will take a look.

**Comment by Shubodh** [comment]
@Skydes Could you expand on what you mean by "It is outdated"? Do you mean there is a better way of doing PR #190 , i.e. better masking approach? Any references would help.

**Comment by Skydes** [comment]
It is outdated in the sense that `extract_features` has seen many changes on the main branch. You might want to load the masks in the dataloader for better performance.
