### ISSUE TITLE
Install from the pip repo

### ISSUE THREAD

**Issue by RandomPrototypes** [cvg/Hierarchical-Localization#252]
Hello,
I'm currently writing a PR to integrate hloc in nerf studio. To get an easy/clean install, the best would be to install it automatically through the dependencies.

I saw this repo on PyPI : https://pypi.org/project/hloc-mod/
Is it an official/safe repo to use for dependency?

thanks

**Comment by Skydes** [comment]
Hey, adding hloc to nerfstudio is great, thanks a lot! hloc is currently not compatible with PyPI but I will look into this soon. The hloc-mod package is broken and not maintained by me - I'm in the process of requesting to take it down.

**Comment by RandomPrototypes** [comment]
Thanks for the answer. I modified my PR for nerfstudio so that hloc an optional dependency that the users can install it manually.

I looked at pixsfm, it seems interesting. I'll try to integrate it too and make a second PR for it.
