### ISSUE TITLE
Colmap with HLoc fails to reconstruct any model

### ISSUE THREAD

**Issue by alex-klimov** [cvg/Hierarchical-Localization#256]
For given set of photos the pipeline of hloc+colmap fails to reconstruct any model. Configuration used:
```python
retrieval_conf = extract_features.confs['netvlad']
feature_conf = extract_features.confs['superpoint_aachen']
matcher_conf = match_features.confs['superglue']
```

Regular stock colmap pipeline with SIFT features works fine, albeit slower.

Where should I look for the root cause? I looked at colmap.db so far. HLoc is creating ~780 records in two_view_geometries table with non-zero matches, while colmap is creating ~9500 pairs in two_view_geometries table with non-zero SIFT matches for the same set of images. Could this be the reason/the main difference, why colmap cannot reconstruct the model from HLoc input?

**Comment by Skydes** [comment]
Apologies for the late reply. How are the image pairs computed? How many images are retrieved per query? If you ran `pipeline_SfM.ipynb`, consider setting `num_matched` to 20-50.

**Comment by alex-klimov** [comment]
Thank you! I will experiment, when I'm back with hloc.
