### ISSUE TITLE
Affter "git clone" the repository, run "demo.ipynb". I received error messages: ModuleNotFoundError: No module named 'SuperGluePretrainedNetwork.models'

### ISSUE THREAD

**Issue by BenoitKAO** [cvg/Hierarchical-Localization#258]
Thank you for your marvelous work!

However, after "git clone" the repository, run "demo.ipynb".
I received error messages:

---
[2023/01/07 13:59:11 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-r1024',
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 extract_features.main(feature_conf, images, image_list=references, feature_path=features)
      2 pairs_from_exhaustive.main(sfm_pairs, image_list=references)
      3 match_features.main(matcher_conf, sfm_pairs, features=features, matches=matches)

File lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File GitHub/Hierarchical-Localization/hloc/extract_features.py:245, in main(conf, image_dir, export_dir, as_half, image_list, feature_path, overwrite)
    242     return feature_path
    244 device = 'cuda' if torch.cuda.is_available() else 'cpu'
--> 245 Model = dynamic_load(extractors, conf['model']['name'])
    246 model = Model(conf['model']).eval().to(device)
    248 loader = torch.utils.data.DataLoader(
    249     dataset, num_workers=1, shuffle=False, pin_memory=True)

File Hierarchical-Localization/hloc/utils/base_model.py:39, in dynamic_load(root, model)
     37 def dynamic_load(root, model):
     38     module_path = f'{root.__name__}.{model}'
---> 39     module = __import__(module_path, fromlist=[''])
     40     classes = inspect.getmembers(module, inspect.isclass)
     41     # Filter classes defined in the module

File Hierarchical-Localization/hloc/extractors/superpoint.py:8
      5 from ..utils.base_model import BaseModel
      7 sys.path.append(str(Path(__file__).parent / '../../third_party'))
----> 8 from SuperGluePretrainedNetwork.models import superpoint  # noqa E402
     11 # The original keypoint sampling is incorrect. We patch it here but
     12 # we don't fix it upstream to not impact exisiting evaluations.
     13 def sample_descriptors_fix_sampling(keypoints, descriptors, s: int = 8):

ModuleNotFoundError: No module named 'SuperGluePretrainedNetwork.models'
The we run incremental Structure-From-Motion and display the reconstructed 3D model.

---
I have referenced the previously solved issue:
https://github.com/cvg/Hierarchical-Localization/issues/228

Nevertheless, copying files from this repository to the current folder did not work.

I would appreciate any help.

**Comment by BenoitKAO** [comment]
I figured it out and solved it.
Thanks~

**Comment by h3fx111** [comment]
> I figured it out and solved it. Thanks~

Hello, could you tell me how you solved it?
