### ISSUE TITLE
Unit of the localization result

### ISSUE THREAD

**Issue by feiyangsuo** [cvg/Hierarchical-Localization#268]
First of all, thanks for your great works!
Using [the colab script](https://colab.research.google.com/drive/1MrVs9b8aQYODtOGkoaGNF9Nji3sbCNMQ) I got a localization result `pose` whose projection_center is `array([-0.20654798,  0.5471504,  3.04778433])`. 
I'm wondering if the unit of these values is clear. Say, they are millimeters, centimeters or meters? Or is the unit ambiguous?
If the unit is ambiguous, is there a way to retrieve it?

**Comment by Skydes** [comment]
The SfM poses are up to an arbitrary scale, so the translation values are in an arbitrary unit.

**Comment by GhYang0519** [comment]
Is there any way to get an accurate real-world pose?
