### ISSUE TITLE
How to use LoFTR in SFM pipeline?

### ISSUE THREAD

**Issue by ZezhouCheng** [cvg/Hierarchical-Localization#275]
Thanks for the great work!  Is it possible to replace Superpoint+Superglue with LoFTR in an SfM pipeline? Is there any guidance on this?

**Comment by Skydes** [comment]
Yes, there's an example here:
https://github.com/cvg/Hierarchical-Localization/blob/61e0cd04dbc63d1beba1f8ed6c03e95937a76dab/hloc/pipelines/Aachen_v1_1/pipeline_loftr.py#L41-L43

**Comment by ZezhouCheng** [comment]
Wonderful, thanks!
