### ISSUE TITLE
How to change the camera model from "SIMPLE_RADIAL" to "PINHOLE"?

### ISSUE THREAD

**Issue by anterrrr** [cvg/Hierarchical-Localization#278]
![image](https://github.com/cvg/Hierarchical-Localization/assets/130300209/7a4d755c-1a53-4c45-8f75-023084ec55f1)

**Comment by anterrrr** [comment]
How can i reconstruct one sfm model by hinpole in the holc.reconstruction?

**Comment by Skydes** [comment]
```python
model = reconstruction.main(..., image_options=dict(camera_model='PINHOLE'))
```
or via CLI:
```bash
python -m hloc.reconstruction [...] --image_options camera_model='"PINHOLE"'
```
See https://github.com/cvg/Hierarchical-Localization/pull/210.

**Comment by anterrrr** [comment]
Thinks a lot
