### ISSUE TITLE
reconstrution problem

### ISSUE THREAD

**Issue by kaiyi98** [cvg/Hierarchical-Localization#292]
hello！
I have sequence images from one camera，and I want to reconstruction the map，but have problem：
`[2023/07/18 17:02:50 hloc WARNING] The database already exists, deleting it.
[2023/07/18 17:02:50 hloc INFO] Creating an empty database...
[2023/07/18 17:02:50 hloc INFO] Importing images into the database...
[2023/07/18 17:04:19 hloc INFO] Importing features into the database...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 798/798 [00:00<00:00, 1380.84it/s]
[2023/07/18 17:04:19 hloc INFO] Importing matches into the database...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3975/3975 [00:02<00:00, 1663.16it/s]
[2023/07/18 17:04:22 hloc INFO] Performing geometric verification of the matches...
[2023/07/18 17:06:03 hloc INFO] Running 3D reconstruction...
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0718 17:10:16.690937 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.693892 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.705538 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.708473 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.728768 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.740311 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.743264 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:16.754990 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:17.714985 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:17.730002 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:17.747335 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W0718 17:10:17.764398 19344 [levenberg_marquardt_strategy.cc:123](http://levenberg_marquardt_strategy.cc:123/)] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.`

I don‘t know why this is happening.

**Comment by Skydes** [comment]
This is just a warning log, the reconstruction process should still work correctly.

**Comment by kaiyi98** [comment]
> This is just a warning log, the reconstruction process should still work correctly.

thank you very much！

**Comment by chris-aeviator** [comment]
hijacking this issue, what is
``
`InitGoogleLogging`


about?

**Comment by sarlinpe** [comment]
This is from [glog](https://github.com/google/glog). We're updating pycolmap/colmap such that this warning doesn't show up.
