### ISSUE TITLE
3D reconstruction result is not good

### ISSUE THREAD

**Issue by rann1018** [cvg/Hierarchical-Localization#30]
Hi, 

I followed your direction to run 3D reconstruction on south-building dataset. I got the mean_reproj_error: 1.400.
However, when I rebulit the same scene using COLMAP with default settings, I got the mean_reproj_error: 0.591.
I do not understand why there is such a huge gap between these two results. I think the 3D reconstruction result of superpoint+superglue should have been better, as accurate 3D model can do good to image relocalization.

Looking forward for your help.

**Comment by Skydes** [comment]
These numbers are expected. Other metrics should be looked at, such as the track length or the number of 3D points. We do not claim that SP+SG is better than SIFT for all SfM metrics, especially with this easy dataset. Keypoint detectors that do not have subpixel localization have a larger reprojection error, which is indeed detrimental for localization [(see this paper)](https://arxiv.org/abs/2003.08348).

**Comment by rann1018** [comment]
Thanks for your reply.

The other metrics also perform worse, such as number of 3D points and mean track length. I do not report these statistics as I think the detected feature number is different.
Besides, I conduct sfm on large-scale Aachen outdoor dataset following your direction.  The SIFT model has the following statistics: Points 1652687; Mean track length 6.387; Mean reprojection error 1. And the SP + SG model has the following statistics: Points 1310593;  Mean track length 6.116; Mean reprojection error 1.452. For 3D reconstruction, SIFT model performs totally better. I do not understand how can a less accurate 3D model lead to better image pose estimation.

Thanks a lot for your attention.

**Comment by Skydes** [comment]
As far as I know, on Aachen the SIFT model was obtained with exhaustive matching while here the SP+SG model uses only the 20 most covisible image pairs - so the results are not really comparable. You can also improve the results by resizing the images to a higher resolution, [as done in the dev branch](https://github.com/cvg/Hierarchical-Localization/blob/dev/hloc/extract_features.py#L37-L51) for Aachen v1.1.

Regarding your question: for day-night localization, invariance to illumination changes is more important than 3D model accuracy. SP+SG might produce 3D models that are less accurate than SIFT, but it is much more invariant and robust than SIFT, and thus overall better suited for day-night localization. There are some recent works ([Dusmanu et al.](https://arxiv.org/abs/2003.08348), [Zhou et al.](https://arxiv.org/abs/2012.01909)) that refine keypoints and obtain more accurate 3D models, which further improves the localization accuracy.

**Comment by rann1018** [comment]
Thanks a lot for your very detailed response!
