### ISSUE TITLE
How can I generate SfM model?

### ISSUE THREAD

**Issue by YanAwithU** [cvg/Hierarchical-Localization#301]
Hi!
First, I appreciate for your works.
I'm just beginner about this field.

I'm currently researching about the effect of noised camera pose on SfM and relocalization.
I already made the GT to noised pose on 7scenes.
But I can not find the way to generate SfM model with noised GT.
The only thing I can find is just pipeline with image input.
Is there the camera pose input in that pipeline?

**Comment by Skydes** [comment]
You can easily load the COLMAP model and perturb the camera poses:
```python
rec = pycolmap.Reconstruction("path/to/my/reconstruction/")
for image_id, image in reconstruction.images.items():
  rotvec = np.random.randn(3)
  qvec = pycolmap.rotmat_to_qvec(cv2.Rodrigues(rotvec))
  tvec = np.random.randn(3)
  image.qvec, image.tvec = pycolmap.concatenate_poses(qvec, tvec, image.qvec, image.tvec)
rec.write("path/to/new/reconstruction/")
```
(up to some typos)

**Comment by YanAwithU** [comment]
Thank you for kind response! I'll try it :)
