### ISSUE TITLE
object 'global_descriptor' doesn't exist

### ISSUE THREAD

**Issue by runningneverstop** [cvg/Hierarchical-Localization#304]
find a problem. How can i solve it?
![image](https://github.com/cvg/Hierarchical-Localization/assets/86957090/3675ef66-267e-45fa-86b7-7e48d3bf5b4d)

**Comment by rogerhh** [comment]
I am running into the same issue. Were you able to resolve this issue?

**Comment by molegod** [comment]
@rogerhh do you have a solution to this issue?
