### ISSUE TITLE
Localization Result

### ISSUE THREAD

**Issue by monamourvert** [cvg/Hierarchical-Localization#313]
Hi, I have question regarding the localization result. I have two cases:

1. Query images is same with the database image (just want to check the pipeline is works or not)
2. Query images is different (not that much) with the database.

The first case went well. The pipeline succeed to localize all query image. But somehow in 2nd case, from 393 query images only 320 images that succeed to localize. I checked the pair file and those missing query pair do not have pair in db images instead having the pair on query image itself. In this kind of case, how can we calculate the accuracy of our localization result? Do we just ignore the 73 images? 

The figure below shows the pair list. Frame 333 and 243 is not written on the localization result

![image](https://github.com/cvg/Hierarchical-Localization/assets/121480926/d187efe1-61cd-44e6-b727-8f98e5978866)

**Comment by sarlinpe** [comment]
How do you generate the image pairs? are you using `pairs_from_retrieval`? If so, you need to explicitly generate pairs from queries to map:
```python
pairs_from_retrieval.main(
    descriptors_path, pairs_path, num_pairs, query_prefix='query', db_prefix='frame')
```

**Comment by monamourvert** [comment]
Thanks! It solved now!
