### ISSUE TITLE
How to separate online and offline

### ISSUE THREAD

**Issue by Adolfhill** [cvg/Hierarchical-Localization#333]
Thanks to your impressive work!

As you mentioned in the paper, there are two parts of the system: online and offline.
Obviously, Offline need lots of time but online just need several ms.
So, I need to do offline just one time and using the result to get 6DOF pose(Online) in a high frequency.
could you please tell me how to do that?

**Comment by superify** [comment]
hi，Do you have any ieda about this? I need some help
