### ISSUE TITLE
Extract camera.txt and images.txt file

### ISSUE THREAD

**Issue by hungvipqt15** [cvg/Hierarchical-Localization#341]
Can I export the camera.txt and images.txt file by HLoc as using COLMAP?

**Comment by sarlinpe** [comment]
With pycolmap:
```python
import pycolmap
pycolmap.Reconstruction(path).write_text(path)
```

**Comment by messileonardo** [comment]
Please, could you provide an example for exporting for example "images.txt"?
Thanks
