### ISSUE TITLE
demo hloc Colab file not working

### ISSUE THREAD

**Issue by LAGWAG** [cvg/Hierarchical-Localization#348]
Hey guys,

The following error is present on the Google Colab script demo hloc. This did not seem to be present a couple weeks ago.

![hloc](https://github.com/cvg/Hierarchical-Localization/assets/153782150/1f3faae3-1173-4802-ac3f-e08e12169df0)

**Comment by mnmanh01** [comment]
You have to use pycolmap>=0.3.0,<=0.4.0 (released v0.5.0 4 days ago)
Add this line to the top of the colab file:
!pip install pycolmap==0.4.0

**Comment by LAGWAG** [comment]
Thank you, this appears to have resolved the issue. Well done.

**Comment by martinakos** [comment]
I have the same error even after adding 
`!pip install pycolmap==0.4.0`
as the first line in the colab notebook and executing from the beginning.
Any ideas?

**Comment by LAGWAG** [comment]
Add the line after the existing pip install commands, otherwise the old version will be over ridden. This worked for me:

!git clone --quiet --recursive https://github.com/cvg/Hierarchical-Localization/
%cd Hierarchical-Localization
!pip install --progress-bar off --quiet -e .
!pip install --progress-bar off --quiet --upgrade plotly
!pip install pycolmap==0.4.0

**Comment by martinakos** [comment]
That works. Thanks!
