### ISSUE TITLE
Sift based local feature extraction is not working bcause of update in pycolmap.

### ISSUE THREAD

**Issue by prasad-pr-20** [cvg/Hierarchical-Localization#352]
The local feature extractor SIFT based DOG extractor class model in hloc/extractors/dog.py seems to be now broken becuase of the update in the pycolmap.
With the latest pycolmap 0.5.0, pycolmap.sift.extract returns only two parameters while three are expected in the current code.
`keypoints, scores, descriptors = self.sift.extract(image_np)`. Upon execution, we get the below error:
> ValueError: not enough values to unpack (expected 3, got 2)

Upon performing a quick RCA, we observed that the current pycolmap i.e., 0.5.0 version, returns just keypoints and descriptors and omits scores, which is the reason for the breakdown.

Any suggestion/fix on how to obtain the score value or fix the existing solution is greatly appreciated.
Thanks in advance.

**Comment by sarlinpe** [comment]
Will be fixed in https://github.com/cvg/Hierarchical-Localization/pull/353

**Comment by sarlinpe** [comment]
https://github.com/cvg/Hierarchical-Localization/pull/353 has been merged.
