### ISSUE TITLE
'pycolmap.Image' object has no attribute 'rotmat'

### ISSUE THREAD

**Issue by vitalii-p** [cvg/Hierarchical-Localization#357]
I got an error during visualization ([viz_3d.plot_reconstruction](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/viz_3d.py#L152))

'pycolmap.Image' object has no attribute 'rotmat'

Could you suggest how to fix such issue?

**Comment by vitalii-p** [comment]
Seems like here it is
`
image.cam_from_world.rotation.matrix().real`

**Comment by sarlinpe** [comment]
https://github.com/cvg/Hierarchical-Localization/pull/353 has been merged.

**Comment by Zeng-Fan-Yi** [comment]
Sorry, but I still got the same error after pulling the latest code and upgrading pycolmap to 0.6.0
 ` 'pycolmap.Image' object has no attribute 'rotmat'`
 The error is probably in the reconstruction section.
 Hope you can help me solve this problem.
 `(SparseReconActor pid=6284) ==============================================================================
(SparseReconActor pid=6284) Global bundle adjustment
(SparseReconActor pid=6284) ==============================================================================
(SparseReconActor pid=6284) I20240130 07:37:35.618382 15876 misc.cc:205]
(SparseReconActor pid=6284) Bundle adjustment report
(SparseReconActor pid=6284) ------------------------
(SparseReconActor pid=6284) I20240130 07:37:35.618382 15876 bundle_adjustment.cc:942]
(SparseReconActor pid=6284)     Residuals : 34964
(SparseReconActor pid=6284)    Parameters : 13447
(SparseReconActor pid=6284)    Iterations : 4
(SparseReconActor pid=6284)          Time : 0.302963 [s]
(SparseReconActor pid=6284)  Initial cost : 0.858948 [px]
(SparseReconActor pid=6284)    Final cost : 0.858513 [px]
(SparseReconActor pid=6284)   Termination : Convergence
(SparseReconActor pid=6284)
(SparseReconActor pid=6284) I20240130 07:37:35.636194 15876 incremental_mapper.cc:175] => Completed observations: 1
(SparseReconActor pid=6284) I20240130 07:37:35.643179 15876 incremental_mapper.cc:178] => Merged observations: 0
(SparseReconActor pid=6284) I20240130 07:37:35.648164 15876 incremental_mapper.cc:160] => Filtered observations: 3
(SparseReconActor pid=6284) I20240130 07:37:35.648164 15876 incremental_mapper.cc:119] => Changed observations: 0.000229
(SparseReconActor pid=6284) I20240130 07:37:35.648164 15876 incremental_mapper.cc:167] => Filtered images: 0
(SparseReconActor pid=6284) I20240130 07:37:35.649194 15876 timer.cc:91] Elapsed time: 0.377 [minutes]
(SparseReconActor pid=6284) [2024/01/30 07:37:35 hloc INFO] Reconstructed 1 model(s).
(SparseReconActor pid=6284) [2024/01/30 07:37:35 hloc INFO] Largest model is #0 with 40 images.
(SparseReconActor pid=6284) [2024/01/30 07:37:35 hloc INFO] Reconstruction statistics:
(SparseReconActor pid=6284) Reconstruction:
(SparseReconActor pid=6284)     num_reg_images = 40
(SparseReconActor pid=6284)     num_cameras = 1
(SparseReconActor pid=6284)     num_points3D = 4404
(SparseReconActor pid=6284)     num_observations = 17480
(SparseReconActor pid=6284)     mean_track_length = 3.96912
(SparseReconActor pid=6284)     mean_observations_per_image = 437
(SparseReconActor pid=6284)     mean_reprojection_error = 1.38667
(SparseReconActor pid=6284)     num_input_images = 40
2024-01-30 07:37:41.826 | WARNING  | auto_decomp.sfm.sfm:main:632 | - [custom_data_example/co3d_chair] Unknown error: 'pycolmap.Image' object has no attribute 'rotmat'`
