### ISSUE TITLE
'pycolmap.Image' object has no attribute 'transform_to_image'

### ISSUE THREAD

**Issue by oxyhexagen** [cvg/Hierarchical-Localization#367]
This issue arises at the last line of the sfm pipeline
`visualization.visualize_sfm_2d(model, images, color_by="depth", n=5)`
```
Traceback (most recent call last):
  File "D:\path2\Hierarchical-Localization\test_pipeline.py", line 47, in <module>
    visualization.visualize_sfm_2d(model, images, color_by="depth", n=5)
  File "D:\path2\Hierarchical-Localization\hloc\visualization.py", line 49, in visualize_sfm_2d
    [
  File "D:\path2\Hierarchical-Localization\hloc\visualization.py", line 50, in <listcomp>
    image.transform_to_image(reconstruction.points3D[j].xyz)[-1]
AttributeError: 'pycolmap.Image' object has no attribute 'transform_to_image'
```

https://github.com/cvg/Hierarchical-Localization/blob/936040e8d67244cc6c8c9d1667701f3ce87bf075/hloc/visualization.py#L48
I couldn't find this function anywhere. 
![search](https://github.com/cvg/Hierarchical-Localization/assets/29267562/8761ce0b-1f7b-471c-b4c1-29e1c05a366d)

And referenced another issue #357 but I'm not sure if my implementation is correct:
```python
z = np.array(
    [
        # image.transform_to_image(reconstruction.points3D[j].xyz)[-1]
        (image.cam_from_world.rotation.matrix() @ reconstruction.points3D[j].xyz + image.cam_from_world.translation)[-1]
        for j in p3ids
    ]
)
```
![Figure_2](https://github.com/cvg/Hierarchical-Localization/assets/29267562/84ab9045-60c1-4629-9f88-e202dbb04ec2)

**Comment by sarlinpe** [comment]
Thank you for reporting this, I just fixed it in https://github.com/cvg/Hierarchical-Localization/commit/0eee565379159d1377bdf39129a8239c42d1b4b1.
