### ISSUE TITLE
Error downloading D2-Net pre-trained model

### ISSUE THREAD

**Issue by crcz25** [cvg/Hierarchical-Localization#368]
I encountered an error while trying to download the D2-Net pre-trained model using the provided notebook _pipeline_SfM.ipynb_. Below is the error message:

![error_d2net](https://github.com/cvg/Hierarchical-Localization/assets/31625277/d048eefd-5736-4bdc-a5fb-e41d1cd7989e)

It seems like there is an issue with the command `wget` returning a non-zero exit status 4. I believe this error is impeding the successful download of the model.

**Steps to Reproduce:**

1. Modify the _setup cell_ where the paths and the configuration of the extractor and matcher are set with the following: 
```
images = Path("datasets/South-Building/images/")
outputs = Path("outputs/sfm/")
sfm_pairs = outputs / "pairs-netvlad.txt"
sfm_dir = outputs / "sfm_d2net+ratio"
retrieval_conf = extract_features.confs["netvlad"]
feature_conf = extract_features.confs["d2net-ss"]
matcher_conf = match_features.confs["NN-ratio"]
```
2. Execute the notebook as usual.
3. Observe the error message mentioned above.

**Expected Behavior:**  
The D2-Net pre-trained model should be downloaded successfully without any errors.

**Additional Information:**  
- Operating System: Ubuntu 20.04.6 LTS
- Python Version: Python 3.10.13

Thank you for your attention to this matter. Please reach out to me if any further information is needed to address this issue.

Best Regards,
Carlos

**Comment by sarlinpe** [comment]
PR https://github.com/cvg/Hierarchical-Localization/pull/369 should fix your issue.
