### ISSUE TITLE
How to specify the camera model for images?

### ISSUE THREAD

**Issue by huzujun** [cvg/Hierarchical-Localization#37]
Thanks for your amazing work. 
I'm trying to do SfM reconstruction for an unordered set of images. I have run the pipeline_SfM.ipynb and found that the default camera model is SIMPLE_RADIAL. However, my dataset is made up of images from a fisheye lens. I wonder if I can specify the camera model for images? In COLMAP, I can do that by adding parameters -ImageReader.camera_model OPENCV_FISHEYE and -ImageReader.single_camera_per_folder. Can I do similar work with hloc?
I review your code and I couldn't find the answer I wanted. It would be really nice if you could give me some suggestions.

**Comment by Skydes** [comment]
Images are parsed and added to the database in the `feature_importer`, which is [called in reconstruction.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/reconstruction.py#L37-L43). There you can add arguments for the `ImageReader`, such as `camera_model` or `single_camera_per_folder`. There is already an argument for `single_camera`.

**Comment by huzujun** [comment]
> Images are parsed and added to the database in the `feature_importer`, which is [called in reconstruction.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/reconstruction.py#L37-L43). There you can add arguments for the `ImageReader`, such as `camera_model` or `single_camera_per_folder`. There is already an argument for `single_camera`.

Thanks a lot.

**Comment by cduguet** [comment]
This has changed ever since. There is no feature_importer anymore. How do you specify the camera model now? 
Thank you!

**Comment by Skydes** [comment]
`pycolmap.import_images` [accepts a `camera_model: str` argument](https://github.com/colmap/pycolmap/blob/34541c45dce80bf18076dd158d9e7380fe4a16cd/pipeline.cc#L212-L219):
https://github.com/cvg/Hierarchical-Localization/blob/e8ea8a25b297bae2e058abfb294335219d9f55ad/hloc/reconstruction.py#L31-L32
