### ISSUE TITLE
Aachen Day-Night v1.1 dataset

### ISSUE THREAD

**Issue by angshine** [cvg/Hierarchical-Localization#38]
Hi, thanks for the great work!

I found an HLoc + SuperGlue submission on the [Aachen Day-Night v1.1 dataset](https://www.visuallocalization.net/benchmark/). Could you open-source the covisible pairs and retrieval pairs for the Aachen v1.1 dataset?

**Comment by Skydes** [comment]
Hi again,
Sorry for the late reply. Support for Aachen v1.1 is only in the `dev` branch for now. The pairs are [here](https://github.com/cvg/Hierarchical-Localization/tree/dev/pairs/aachen_v1.1) and there is a notebook with the simplified steps. Hope this helps!

**Comment by angshine** [comment]
Thanks!
