### ISSUE TITLE
i can't setup.py

### ISSUE THREAD

**Issue by applefb** [cvg/Hierarchical-Localization#386]
ERROR: Could not find a version that satisfies the requirement lightglue (unavailable) (from hloc) (from versions: none)
ERROR: No matching distribution found for lightglue (unavailable)

**Comment by applefb** [comment]
I can install hloc on Windows, but I will encounter errors when installing on Ubuntu22.04

ERROR: Could not find a version that satisfies the requirement lightglue (unavailable) (from hloc) (from versions: none)
ERROR: No matching distribution found for lightglue (unavailable)

**Comment by applefb** [comment]
i fixed
python -m pip install --upgrade setuptools
python -m pip install --no-build-isolation -e .

but i want to know why

**Comment by applefb** [comment]
[https://github.com/cvg/LightGlue/issues/104](url)

**Comment by antithing** [comment]
> I can install hloc on Windows, but I will encounter errors when installing on Ubuntu22.04
> 
> ERROR: Could not find a version that satisfies the requirement lightglue (unavailable) (from hloc) (from versions: none) ERROR: No matching distribution found for lightglue (unavailable)

Hi @applefb can you share your steps to install on windows?
