### ISSUE TITLE
How to make localization more precise when I use my own datasets

### ISSUE THREAD

**Issue by shuiliuliushui** [cvg/Hierarchical-Localization#39]
Hi, thanks for the great work!
  I want to use hloc to implement a localization task. I followed these steps:
  1. I create my own datasets by indoor images that I capture by my own phone .
  2. I use OpenIBL to create global descriptors.
  3. I use pairs_from_retrieval.py to create dbpairs.txt.
  4. Then, I follow the pipline_SFM to create a model.
  5. Finally, I use this model to localize a new image.
  Unfortunately, I can't achieve a precise result. What should I do to improve it?

**Comment by Skydes** [comment]
What do you mean by "can't achieve a precise result" ? Some pointers:
1. Does the SfM model look ok when visualized in the COLMAP GUI? The topology should be correct and planar areas should roughly be so (e.g. planar ground and walls). Are the estimated camera poses roughly correct too?
2. Does the retrieval work as expected for the queries? It's often useful to visualize a the top-3 retrieved for a few queries. We don't have a code for this yet but it should be easy with [`plot_images`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/viz.py#L21). PR are welcome!
3. Do the matches look reasonable? For this, there are some examples in the notebooks.

**Comment by shuiliuliushui** [comment]
Thanks for your reply.
I find the problem. When I try to localize the query image, I don't use the correct camera parameter. Now the result is pretty good in most of time. But if I capture the same objects from different distance and don't change the viewpoint, the result can't represent the difference of distance very well. 
I think it may because there aren't enough such images in my datasets.  Is that true?

**Comment by Skydes** [comment]
1. Re camera parameters: it is possible to refine the focal length in PnP+RANSAC. This is disabled by default but can be enabled in pycolmap [here](https://github.com/mihaidusmanu/pycolmap/blob/master/absolute_pose.cc#L71). It is also possible to read an initial focal length from the EXIF file (COLMAP does it for reference images) but it's not supported yet. PRs are welcome!
2. Image matching might not work well if there are large scale changes. You might want to check some image pairs and their matches.

**Comment by shuiliuliushui** [comment]
Thanks for your reply.
I'll try it. Thanks a lot.

**Comment by Skydes** [comment]
I am closing this issue, feel free to reopen if you encounter other problems.
