### ISSUE TITLE
Difficulty in Obtaining Accurate Camera Poses in Dynamic Outdoor Urban Scenarios

### ISSUE THREAD

**Issue by arstek131** [cvg/Hierarchical-Localization#396]
I am using a stereo setup to obtain camera poses in a dynamic outdoor urban scenario. Below is the configuration I am currently using:

```
'feature_conf': 'disk',
'matcher_conf': 'disk+lightglue',

model = reconstruction.main(
    sfm_dir,
    images,
    sfm_pairs,
    features,
    matches,
    image_list=references,
    camera_mode='SINGLE',
    image_options={'camera_model': 'SIMPLE_PINHOLE',
                   'camera_params': "{}, {}, {}".format(intrinsics[0,0], intrinsics[0,2], intrinsics[1,2]),
                   },
    mapper_options=dict(ba_refine_focal_length=False, ba_refine_extra_params=False)
)
```

I have also attempted to implement a mask for dynamic objects by following the pull requests opened by other users, but the reconstruction fails, it seems to work in scenes where there are fewer dynamic objects.

Are there any suggested changes or improvements to the current configuration that could enhance the accuracy of camera poses in dynamic scenes?

Thank you!

**Comment by sean880304** [comment]
have you tried superpoint + superglue?

**Comment by arstek131** [comment]
> have you tried superpoint + superglue?

No it's still failing.

However, I found a solution, instead of giving 100/150 images as input, I give the whole scene which consists of about 600 images, and the results seems nice!
