### ISSUE TITLE
How can R2D2 features be matched?

### ISSUE THREAD

**Issue by tworkool** [cvg/Hierarchical-Localization#397]
Hey,
I tried using R2D2 features with a few matching methods like lightglue, superglue and loftr, but none of them seem to match the features and an exception is thrown which I interpret as incompatible r2d2 outputs and matcher inputs. I already looked a bit through the code but I dont have too much time because I need to test other pipelines as well for my masters thesis. This is why I thought I would just ask straight away and maybe somebody knows how to use r2d2 features!

Thanks,
Oliver

**Comment by sarlinpe** [comment]
R2D2 requires NN-ratio or NN-mutual because we don't have deep matchers trained for it.

**Comment by tworkool** [comment]
Thanks! I thought I tried using it with NN but seems I did not
