### ISSUE TITLE
RuntimeWarning during geometric verification and failure in triangulation

### ISSUE THREAD

**Issue by nushakrishnan** [cvg/Hierarchical-Localization#419]
Hello,

I am using the hloc library to triangulate points in my COLMAP model which consists of multiple images from 2 cameras (left and right cameras of a rig). However, during geometric verification of the matches, I face some runtime warnings as shown in the image below. This further results in a failure during 3d triangulation (also shown in the image). I am not sure why this could be happening. Please could I receive some guidance here? Thank you in advance!

![image](https://github.com/user-attachments/assets/9c49fdb4-e9af-4d82-b762-ee532d523225)

**Comment by sarlinpe** [comment]
The warnings are likely unrelated to the error (I agree that they should be fixed though), which is most likely already fixed by https://github.com/colmap/colmap/pull/2704 Just update your COLMAP installation.

**Comment by nushakrishnan** [comment]
Thank you @sarlinpe, the updated COLMAP installation fixed the triangulation error.

**Comment by nushakrishnan** [comment]
Closing issue as it is resolved.
