### ISSUE TITLE
point_triangulator problem

### ISSUE THREAD

**Issue by bixiaopeng0** [cvg/Hierarchical-Localization#42]
Hello,
Thank you for your great work.
When I run pipeline_Aachen ,  use the Aachen dataset.  I face a problem,do you know how to deal it?

_==============================================================================
Triangulating image #1275 (4323)
==============================================================================

  => Image sees 3134 / 3560 points
  => Triangulated 241 points

==============================================================================
Triangulating image #855 (4324)
==============================================================================

  => Image sees 2652 / 2757 points
  => Triangulated 68 points

==============================================================================
Triangulating image #3514 (4325)
==============================================================================

  => Image sees 2534 / 2967 points
  => Triangulated 222 points

==============================================================================
Triangulating image #3771 (4326)
==============================================================================

  => Image sees 3402 / 3634 points
  => Triangulated 193 points

==============================================================================
Triangulating image #1486 (4327)
==============================================================================

  => Image sees 1421 / 1804 points
  => Triangulated 62 points

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 9730
  => Merged observations: 905932

==============================================================================
Bundle adjustment
==============================================================================

[01/31/2021 18:34:39 WARNING] Problem with point_triangulator, exiting.
_

**Comment by Skydes** [comment]
Hi,
Since there are no explicit error messages from COLMAP, I suspect that the point triangulator was simply killed by the OS, for example after running out of memory. Could you run this step again closely monitoring your system memory?
Additionally: please use code fences to report output logs here.
Thanks.

**Comment by bixiaopeng0** [comment]
thanks for your reply.How much memory is needed to run this code.

**Comment by Skydes** [comment]
I really depends on the data and on the hardware. For this specific dataset, I don't know. You can check it on your own machine.

**Comment by bixiaopeng0** [comment]
thanks, I will try
