### ISSUE TITLE
KeyError: 'Unable to open object (component not found)'

### ISSUE THREAD

**Issue by NhatUS03** [cvg/Hierarchical-Localization#433]
In Pipeline_Inloc, I have a problem in the "Match the Query Images" cell. The errors are as follows:
<img width="1153" alt="Snipaste_2024-10-28_17-01-33" src="https://github.com/user-attachments/assets/68f537af-8005-4fcf-b5c5-71856babdf06">. This error originates from line 239 in match_features.py (specifically, for idx, data in enumerate(tqdm(loader, smoothing=0.1))). If anyone has encountered the same problem, could you please provide solutions?

**Comment by reynoldscem-oculo** [comment]
I'm having the same issue.

**Comment by NhatUS03** [comment]
> I'm having the same issue.
Did you find the solution ? But in my case, I installed missing 'scans' folder :<

**Comment by reynoldscem-oculo** [comment]
@NhatUS03 I see you closed this, did you find the solution? For me it was inconsistency with folders / image lists
