### ISSUE TITLE
bugs in whiten features?

### ISSUE THREAD

**Issue by zjhthu** [cvg/Hierarchical-Localization#44]
There might be a bug in [whiten feautres](https://github.com/cvg/Hierarchical-Localization/blob/dev/hloc/extractors/dir.py#L73). 
We should pass `**self.conf['whiten_params']` to the `whiten_features` function, rather than `self.conf['whiten_params']`. Ohtherwise, this parameter is actually passed to [l2norm](https://github.com/naver/deep-image-retrieval/blob/278e7081364669c1e4e137a9ea6a0840ed0cf2bf/dirtorch/utils/common.py#L235), and the parameters will not take effect.

**Comment by Skydes** [comment]
Good catch. Given the default params, this only changes the `whitenp` from `0.25` to `0.5`, which should have minor impact. I will reevaluate and update (the new retrieval feature anyway needs more doc).

**Comment by Skydes** [comment]
Fixed in https://github.com/cvg/Hierarchical-Localization/commit/99e0fd88ae78acc8c09c0fbb6d61f1805b0777f5.
