### ISSUE TITLE
Inloc dataset

### ISSUE THREAD

**Issue by kxhit** [cvg/Hierarchical-Localization#5]
Hi! Sorry to disturb you.
When I try to evaluate inloc dataset, an error occurs 
`No such file or directory 'database/alignments/DUC1/transformations/DUC_trans_024.txt`. 
I check my downloads and still can't find these .txt files. Could you tell me where I can download / find them? Thanks!

**Comment by Skydes** [comment]
The expected database file structure of `datasets/inloc/` is:
```
.
├── database
│   ├── alignments
│   └── cutouts
└── query
    └── iphone7
```
As explained [here](https://github.com/HajimeTaira/InLoc_dataset#usage), the `alignments` folder corresponds to transformation matrices that can be downloaded [on the WUSTL webpage](https://cvpr17.wijmans.xyz/data/).

**Comment by kxhit** [comment]
Many thanks!!!
I get results below, which is a little different from yours but is indeed a great baseline. Cheers! 

Aachen dataset:


Method | day | night
-- | -- | --
hloc | 89.3 / 96.0 / 98.5 | 84.7 / 91.8 / 100.0


Inloc dataset:


Method | duc1 | duc2
-- | -- | --
hloc | 47.0 / 66.7 / 78.3 | 51.9 / 71.8 / 77.9
