### ISSUE TITLE
Please help me to solve this problem .

### ISSUE THREAD

**Issue by cks3443** [cvg/Hierarchical-Localization#54]
**match_features.main(matcher_conf, sfm_pairs, feature_conf['output'], outputs)**

### When the above code is executed, the following error occurs.

[03/02/2021 15:30:27 INFO] Matching local features with configuration:
{'model': {'name': 'superglue',
           'sinkhorn_iterations': 50,
           'weights': 'outdoor'},
 'output': 'matches-superglue'}
  0%|          | 0/85515 [00:00<?, ?it/s]
Loaded SuperGlue model ("outdoor" weights)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-2265bc492996> in <module>
----> 1 match_features.main(matcher_conf, sfm_pairs, feature_conf['output'], outputs)

/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     24         def decorate_context(*args, **kwargs):
     25             with self.__class__():
---> 26                 return func(*args, **kwargs)
     27         return cast(F, decorate_context)
     28 

~/Hierarchical-Localization/hloc/match_features.py in main(conf, pairs, features, export_dir, exhaustive)
     87 
     88         data = {}
---> 89         feats0, feats1 = feature_file[name0], feature_file[name1]
     90         for k in feats1.keys():
     91             data[k+'0'] = feats0[k].__array__()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/usr/local/lib/python3.8/dist-packages/h5py/_hl/group.py in __getitem__(self, name)
    286                 raise ValueError("Invalid HDF5 object reference")
    287         else:
--> 288             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    289 
    290         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: 'Unable to open object (component not found)'

**Comment by Skydes** [comment]
This might happen if the code crashed a first time. You might need to delete the match file before running it again. Can you confirm that this happens?

**Comment by cks3443** [comment]
This problem was generated with wrong image inputs.

Thank you. Skydes

**Comment by iwander-all** [comment]
I get same problem following the readme of pipeline aachen_v_1_1, I think when run the demo, we cannot use the images_upright/ from aachen_v1_1.zip but from database_and_query_images.zip, right ?
