### ISSUE TITLE
match_features is very slow

### ISSUE THREAD

**Issue by shliang0603** [cvg/Hierarchical-Localization#55]
@Skydes Hi, I test the pipeline_Aachen.ipynb demo. But the process of feature matching is very slow, taking about ten hours.Is this normal? Can you give me some advice, thank you

My envs:

* Ubuntu18.04
* NVIDIA GPU:  GeForce GTX 1080

![image](https://user-images.githubusercontent.com/37186266/110453490-2cb5e280-8101-11eb-80de-363ec377614b.png)

**Comment by Skydes** [comment]
I don't have runtimes for a 1080 but this doesn't seem unreasonable.
