### ISSUE TITLE
results of superpoint on robotcar

### ISSUE THREAD

**Issue by feixue94** [cvg/Hierarchical-Localization#56]
I tried to test the performance of superpoint with nn matcher on robotcar (provided pairs by branch RobotCar). 
the benchmark (https://www.visuallocalization.net/mysubmissions/) website reports all 0.0s 
spp_nn_r1600	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0	0.0 / 0.0 / 0.0

recovered poses are like this:
1418721354984638.jpg -0.08409175209870641 -0.07357707425962663 0.667339933857952 0.7363235729289312 -96.14146959080932 -19.69592955973628 -11.657507536059468
    2 1418721355075498.jpg -0.08393794956225682 -0.0735266463075483 0.668034188528499 0.7357163691689331 -96.7303956280169 -19.803801379568462 -11.85768066227238
    3 1418721355257224.jpg -0.08478601111039455 -0.07354117958582856 0.6677822756858589 0.7358463559092546 -97.90120915344288 -20.157945493599705 -12.151485883062993
    4 1418721355439072.jpg -0.08416808462252273 -0.07276472068815287 0.6676495142262722 0.7361149061848794 -99.12599589963402 -20.189415259599485 -12.53126523022953
    5 1418721355529934.jpg -0.08424293836935966 -0.0728568479482064 0.6678673339280505 0.7358996068172525 -99.71183828475488 -20.338297703593476 -12.73737957313232
    6 1418721355711782.jpg -0.08636523998204902 -0.07442841140009489 0.6662856667367545 0.7369293502096793 -100.80549167763817 -21.047891867906273 -13.12322086332045
    7 1418721355802644.jpg -0.0876038073171935 -0.07558142251623802 0.6652890159383815 0.7375659609727754 -101.33295481703638 -21.483084419215736 -13.36308792206289

**Comment by Skydes** [comment]
Is that for RobotCar v1 or v2? For the v2, you might need to change the file extension from `jpg` to `png` (although this might have been fixed now).

**Comment by feixue94** [comment]
it is for V1
