### ISSUE TITLE
How to solve the problem: geometric verification failed

### ISSUE THREAD

**Issue by aruba01** [cvg/Hierarchical-Localization#65]
When I run the `aachen.ipynb`, the step "**triangulate a new SfM model from the poses**" always fail because of geometric verification. The colmap function "`matches_importer`" report the error: `SystemExit:1.` I also tried to skip geometric verification, it will error with the colmap function "`point_triangulator`" and report the error `SystemExit:-6`. Please help me, thank you!
![KU OR541WYH 3XEXP}V${GA](https://user-images.githubusercontent.com/47864285/115106857-c3e04680-9f99-11eb-83ce-14ea95e44895.png)
![(0K%759YHS}7YZ V 2M{~K6](https://user-images.githubusercontent.com/47864285/115106862-c8a4fa80-9f99-11eb-97e9-51522aece21a.png)
![S0XS2BW3~ D8O5%UCE7)5E2](https://user-images.githubusercontent.com/47864285/115106865-cb9feb00-9f99-11eb-9f01-248444123529.png)

**Comment by yopi1838** [comment]
I experienced the same problem there. One thing that I can think of is that the script couldn't find the path to COLMAP. maybe try define them as environment variable instead?

**Comment by Skydes** [comment]
Thanks for reporting this. I should make the error message more explicit. The scripts indeed assume that the COLMAP executable is in the global path as `colmap`. @aruba01 could you please make sure that it is not the issue?

**Comment by aruba01** [comment]
> Thanks for reporting this. I should make the error message more explicit. The scripts indeed assume that the COLMAP executable is in the global path as `colmap`. @aruba01 could you please make sure that this is correct in your case?

I can directly run the commond `colmap -h` and `colmap gui` in terminal. I also thought about the path of colmap, so I changed the `colmap_path` from `colmap_path='colmap'` to `colmap_path='usr/local/bin/colmap'` (you can see it in my previous screenshot), the problem still happened.

**Comment by aruba01** [comment]
> > Thanks for reporting this. I should make the error message more explicit. The scripts indeed assume that the COLMAP executable is in the global path as `colmap`. @aruba01 could you please make sure that this is correct in your case?
> 
> I can directly run the command `colmap -h` and `colmap gui` in terminal. I also thought about the path of colmap, so I changed the `colmap_path` from `colmap_path='colmap'` to `colmap_path='usr/local/bin/colmap'` (you can see it in my previous screenshot), the problem still happened.

I directly run the colmap comand `/usr/local/bin/colmap matches_importer \
	--database_path outputs/aachen/sfm_superpoint+superglue/database.db \
	--match_list_path pairs/aachen/pairs-db-covis20.txt \
	--match_type pairs` (this command is run by scripts) in terminal and find its some problem with qt display. Though I have solved the problem, it still remains problem beacause of the colmap function `point_triangulartor` error: `SystemExit:-6`. I also run this command in terminal, I get the following information. Maybe some steps before make mistakes, but I follow the script step by step.
![EK03XQP O}S{@JADSGL@J06](https://user-images.githubusercontent.com/47864285/115299998-09676400-a192-11eb-866b-cf6dcd1e5e70.png)

**Comment by Skydes** [comment]
The match importer fails because it cannot import OpenGL, which is required for SIFT matching but not here. Could you try to run it with `--use_gpu 0` ?

The triangulator fails because the reconstruction appear empty. If the match importer is skipped, inlier matches should be added manually as [here](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/triangulation.py#L90).

**Comment by aruba01** [comment]
> The match importer fails because it cannot import OpenGL, which is required for SIFT matching but not here. Could you try to run it with `--use_gpu 0` ?
> 
> The triangulator fails because the reconstruction appear empty. If the match importer is skipped, inlier matches should be added manually as [here](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/triangulation.py#L90).

Thanks, now I can run the script completely with skipping geometric verification. But I still want run it without skipping geometric verification. How to run it with `--use gpu 0`, the function `match_importer` doesn't have the option `--use_gpu`.

By the way, where can I see the localization results values of (0.25m, 2°) / (0.5m, 5°) / (5m, 10°)

**Comment by Skydes** [comment]
The parameter is `--SiftMatching.use_gpu 0`. The matches importer should not rely on GPU matching, but the OpenGL context seems nonetheless created according to your logs.

**Comment by aruba01** [comment]
> The parameter is `--SiftMatching.use_gpu 0`. The matches importer should not rely on GPU matching, but the OpenGL context seems nonetheless created according to your logs.

It works! Thanks for your great work!
