### ISSUE TITLE
extracting Feature points by using superpoint model is not good

### ISSUE THREAD

**Issue by zhengshunkai** [cvg/Hierarchical-Localization#67]
hello,thank you for your amazing work.
when i use the model superpoint_v1.pth to extracting Feature points,i found the result is not good,some Feature points in the sky and ground seems not right.as shown in the figure below:
![image](https://user-images.githubusercontent.com/9248030/120737958-98052a00-c521-11eb-948d-d12c4d7bf5dc.png)
the param is:
    'superpoint_aachen': {
        'output': 'feats-superpoint-n4096-r1024',
        'model': {
            'name': 'superpoint',
            'nms_radius': 3,
            'max_keypoints': 4096,
        },
        'preprocessing': {
            'grayscale': True,
            'resize_max':1920,
        },
    },

but when i use the [tensorflow-superpoint](https://github.com/rpautrat/SuperPoint),it seems right:
![image](https://user-images.githubusercontent.com/9248030/120738086-cdaa1300-c521-11eb-960d-d6837596f0fb.png)

Is it my configuration error or something else？thx

**Comment by Skydes** [comment]
What input size are you using for the Tensorflow implementation? Could you compare with the exact input sizes? `'resize_max':1920,` resizes the image to 1920px at most, which is probably too large. You should:
- drop this to 1200-1600 pixels if you care more about very accurate keypoints and are ok with some noisy detections in textureless areas
- drop this to 720-1024 if you prefer to have fewer, more repeatable but less accurate keypoints

**Comment by zhengshunkai** [comment]
Thank you for your reply.

1. The param ` 'resize_max':1920` not used and the first image above(pytorch implementation ) use the input sizes : `540X960(HXW)`
2. The second image above(Tensorflow implementation) use the input sizes:`480X640(HXW)`

In the Tensorflow implementation,I changed the input sizes to `540X960(HXW)`, as shown in the figure below and seems good:
![图片](https://user-images.githubusercontent.com/9248030/120787806-521c8600-c562-11eb-8b77-ff4779aa7f28.png)

**Comment by Skydes** [comment]
There is no significant difference in the results. The Tensorflow model might have been trained with more noise so it has fewer detections in textureless areas. I don't think that this has a large impact on the results.

**Comment by zhengshunkai** [comment]
OK.Thank you very much.
