### ISSUE TITLE
How do I prepare the custom dataset?

### ISSUE THREAD

**Issue by Zumbalamambo** [cvg/Hierarchical-Localization#7]
I have set of images, 6dof positions of images. How do i structure is in such a way that the hfnet requires it to be.

**Comment by Skydes** [comment]
If you already have a 6DoF poses of the images, you simply need to triangulate a new 3D SfM model. This requires:

1. Building a COLMAP reference model. See how to [create cameras](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/colmap_from_nvm.py#L58) and [images](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/colmap_from_nvm.py#L153). You can provide an empty Points3D dictionary (no pointcloud).
2. Establishing a list of matching images:
      1. With exhaustive matching: if you have few (<100) images, see [here](https://nbviewer.jupyter.org/github/cvg/Hierarchical-Localization/blob/master/pipeline_SfM.ipynb#Exhaustive-matching).
      2. Using covisibility of an existing 3D model: if you also have 3D points, see `hloc/pairs_from_covisibility.py`.
      3. Using image retrieval, like [NetVLAD](https://github.com/uzh-rpg/netvlad_tf_open): see instructions [here](https://github.com/cvg/Hierarchical-Localization#using-your-own-image-retrieval).
3. Running the triangulation, similarly as [in the Aachen pipeline](https://nbviewer.jupyter.org/github/cvg/Hierarchical-Localization/blob/master/pipeline_Aachen.ipynb#Triangulate-a-new-SfM-model-from-the-given-poses).

**Comment by Zumbalamambo** [comment]
@Skydes I do have the point cloud as well. Do I still need to use COLMAP? These are the components that I have.

1. Point cloud of the entire rooms.
2. Images with 6dof pose information. These 6DOF poses can pinpoint where exactly the camera is in the point cloud.
3. Camera Intrinsic Parameters.

**Comment by Skydes** [comment]
Yes, we use COLMAP for the triangulation of the SuperPoint+SuperGlue SfM model, and the COLMAP data format for I/O. As described above, first format your data into binary [a COLMAP model](https://colmap.github.io/format.html#sparse-reconstruction). Then run all the steps of the Aachen pipeline.

**Comment by Zumbalamambo** [comment]
I'm still stuck with creating a colab model for hierarchical localization :P I have been trying to follow your guidelines. Is there any documentation or code sample that creates colmap model based on the image data that has got the 6dof pose already? May be with colmap gui?

**Comment by Zumbalamambo** [comment]
I also noticed this function this https://github.com/cvg/Hierarchical-Localization/blob/b005824c90eebaf3392d3ac464964edf5c126344/hloc/colmap_from_nvm.py#L13 

In my case, how shall I structure it accordingly? what must be the camera_id,image_id, and name? :)

**Comment by Skydes** [comment]
This function is used if a COLMAP database is already available. In your case: iterate through your images, and create a new [`Camera`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/colmap_from_nvm.py#L58) and [`Image`](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/colmap_from_nvm.py#L153) for each. Pick a unique integer id for each, e.g. `camera_id = image_id = index_of_the_image`, and use the filename of the image as the `name`. Also iterate though the pointcloud, create a [`Point3D`](https://github.com/cvg/Hierarchical-Localization/blob/b005824c90eebaf3392d3ac464964edf5c126344/hloc/colmap_from_nvm.py#L114) for each point, also with an id, and fill in the covisibility information that links images and points.

**Comment by Zumbalamambo** [comment]
@Skydes thank you!... I'm doing it currently. May I know what is [params](https://github.com/cvg/Hierarchical-Localization/blob/b005824c90eebaf3392d3ac464964edf5c126344/hloc/colmap_from_nvm.py#L54) ?

**Comment by Skydes** [comment]
How did you obtain the camera intrinsics? The camera models are described [here](https://colmap.github.io/cameras.html), pick one that corresponds to your calibration. Use SIMPLE_PINHOLE if you have a single focal length, and no distortion.

**Comment by Zumbalamambo** [comment]
@Skydes I calibrated the camera. Also if we use [ARFoundation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/index.html), we could retrieve the camera intrinsic params as well.

**Comment by Zumbalamambo** [comment]
I have followed your advice and created the cameras. However I'm not entirely sure if images and points3d are created properly. My point cloud is in ply format. I have uploaded my code. Please rename it to app.py. Am I doing it properly?


[app.txt](https://github.com/cvg/Hierarchical-Localization/files/5073058/app.txt)

**Comment by Zumbalamambo** [comment]
I have followed your advice and created the cameras. However, I'm not entirely sure if images and points3d are created properly. My point cloud is in ply format. I have uploaded my code. Please rename it to app.py. Am I doing it properly?

[main.txt](https://github.com/cvg/Hierarchical-Localization/files/5073086/main.txt)

**Comment by Shubodh** [comment]
@Zumbalamambo Have you done it? What he mentioned as quoted [above](https://github.com/cvg/Hierarchical-Localization/issues/7#issuecomment-673440237)? 

@Skydes If I have a dataset like InLoc with poses and 3D points for every reference image, is there an example which builds the COLMAP model? I am aware of [pipeline_InLoc.ipynb](https://nbviewer.jupyter.org/github/cvg/Hierarchical-Localization/blob/master/pipeline_InLoc.ipynb) but I am not looking to localize query image. Instead:
I am basically trying to implement "covisibility clustering for InLoc". From what I understand, I can do it in following two ways:
- if I have my data in COLMAP database format, it is very easy to implement covisibility clustering by inputting that COLMAP reconstruction object to [do_covisibility_clustering()](https://github.com/cvg/Hierarchical-Localization/blob/836af6f1dc651fa82ae5062221fdf641ad733004/hloc/localize_sfm.py#L15).
- Otherwise, I can avoid COLMAP format but will have to heavily rewrite `do_covisibility_clustering()` which involves defining unique IDs for Points3D, Camera, Image etc. If I have to do that anyway, I might as well create COLMAP model and just use the `do_covisibility_clustering()` directly?

Let me know if I am on right track and please give further directions.

**Comment by Shubodh** [comment]
I can see [hloc/reconstruction.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/reconstruction.py). Just like how it [import_images](https://github.com/cvg/Hierarchical-Localization/blob/836af6f1dc651fa82ae5062221fdf641ad733004/hloc/reconstruction.py#L26) into COLMAP database, if we could also import poses and 3D points into it in some way (How?), it will be easy for us for datasets like InLoc to implement covisibility clustering as defined in hloc. (i.e. function [do_covisibility_clustering()](https://github.com/cvg/Hierarchical-Localization/blob/836af6f1dc651fa82ae5062221fdf641ad733004/hloc/localize_sfm.py#L15) 

The How? question doesn't seem straightforward, especially given the incomplete/ongoing documentation of [pycolmap](https://github.com/colmap/pycolmap).

**Comment by Shubodh** [comment]
Created [new issue for this](https://github.com/cvg/Hierarchical-Localization/issues/260#issue-1557177121), we can keep this issue closed and continue there instead.
