### ISSUE TITLE
Use other datasets to conduct localization

### ISSUE THREAD

**Issue by ericzzj1989** [cvg/Hierarchical-Localization#80]
Hi, thanks for the great work!
I want to use hloc to implement a localization task. I have other datasets like Phototourism.
Could you please provide some detailed process to use hloc to do localization in Phototourism?

**Comment by Skydes** [comment]
You can follow these steps:
1. Define the split between reference and query images
2. Run SfM on the reference images (see pipeline_SfM.ipynb) or, if you already have reference poses, run triangulation (create an empty COLMAP model and follow pipeline_Aachen.ipynb)
3. Create a text file `query_list_with_intrinsics.txt` that lists the query images and the intrinsics of each. [Here](https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/queries/night_time_queries_with_intrinsics.txt) is an example. The intrinsics follow the [convention of COLMAP](https://colmap.github.io/cameras.html). We do not yet provide tools to obtain the intrinsics as it depends on the data - they are either computed by a built-in SLAM system (e.g. ARKit) or obtained from the phone, camera model, or EXIF data (COLMAP can do this).
4. Run the localization with `hloc.localize_sfm`

**Comment by ericzzj1989** [comment]
Many thanks for your clear explanation. I have already implemented my own datasets.
Another question: is the computed poses (computed from Hierachical Localization) the relative poses from query images w.r.t reference images?

**Comment by ericzzj1989** [comment]
How to define here world coordinates you said?

**Comment by Skydes** [comment]
It is the coordinate system of the SfM poses and 3D point cloud. If you ran SfM yourself, it is pretty much arbitrary.

**Comment by Skydes** [comment]
You can create the reference pairs using image retrieval as well by selecting the same image list for queries and references. `hloc.pairs_from_retrieval` does not remove self-matches (yet, PR welcome) but this should not make much difference.

**Comment by ericzzj1989** [comment]
@Jenny0420 
You can first run hloc.pairs_from_retrieval using only reference images to create the reference pairs, as following example:
pairs_from_retrieval.main(
        *, *, *,
        query_list=reference images, db_list=reference images)

'query_list' and 'db_list' are both assigned as reference img

PS: is it your research interest, visuallocalization?

**Comment by Skydes** [comment]
`pairs_from_retrieval` now handles self-matching correctly to use in SfM https://github.com/cvg/Hierarchical-Localization/pull/136/commits/8664e258b67e65faf0c9ebf39f6515ca01d9ee7d
