### ISSUE TITLE
copy error in exfat flie system

### ISSUE THREAD

**Issue by TxT1212** [cvg/Hierarchical-Localization#87]
**error message:**
>  File "/home/txt/Downloads/loc/Hierarchical-Localization/hloc/pipelines/naverB1/pipeline.py", line 50, in <module>
    triangulation.main(
  File "/home/txt/Downloads/loc/Hierarchical-Localization/hloc/triangulation.py", line 174, in main
    create_empty_model(reference_sfm_model, empty_model)
  File "/home/txt/Downloads/loc/Hierarchical-Localization/hloc/triangulation.py", line 22, in create_empty_model
    shutil.copy(reference_model / 'cameras.bin', empty_model)
  File "/home/txt/anaconda3/envs/text_loc/lib/python3.8/shutil.py", line 419, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/txt/anaconda3/envs/text_loc/lib/python3.8/shutil.py", line 308, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/media/txt/data2/naver/outputs/B1/sfm_superpoint+superglue/empty/cameras.bin'

**reason:**
(maybe) exfat doesn't support symlinks, although it doesn't help to add "follow_symlinks=False" into " shutil.copy(reference_model / 'cameras.bin', empty_model)"

**bypass:**
I remove copy in triangulation.py and copy model manually

**Comment by Skydes** [comment]
Thanks for reporting this issue. [This post](https://stackoverflow.com/questions/11835833/why-would-shutil-copy-raise-a-permission-exception-when-cp-doesnt ) might describe the root cause. Could you please try with copyfile? `shutil.copyfile(reference_model / 'cameras.bin', empty_model / 'cameras.bin')` I will push a fix if this works.

**Comment by TxT1212** [comment]
> Thanks for reporting this issue. [This post](https://stackoverflow.com/questions/11835833/why-would-shutil-copy-raise-a-permission-exception-when-cp-doesnt) might describe the root cause. Could you please try with copyfile? `shutil.copyfile(reference_model / 'cameras.bin', empty_model / 'cameras.bin')` I will push this fix if it works.

copyfile() works. Thanks

**Comment by Skydes** [comment]
Fixed in https://github.com/cvg/Hierarchical-Localization/commit/6c0393ee2382b151c4fc117bfcd23549e262c8bf
