### ISSUE TITLE
Docker build fails during pip3 install opencv-python

### ISSUE THREAD

**Issue by SedMek** [cvg/Hierarchical-Localization#9]
Hello,

I am facing this error while trying to build the provided Dockerfile:

**command**: ` docker build -t hloc:latest .`
**output**: 
`
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/e0/6f/237b730227927c15a68ec831a51bc83837bb65d54bf9651c08b474201b9a/opencv-python-4.4.0.40.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eh82bx8_/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'`

Is there a known way to fix it?

**Comment by Skydes** [comment]
Could you try adding 
```Docker
RUN pip install --upgrade pip
```
before line 7 of the Dockerfile? This seems related to the issue described [here](https://stackoverflow.com/questions/63410588/cant-install-opencv-python3-8).

**Comment by Skydes** [comment]
Fixed by https://github.com/cvg/Hierarchical-Localization/pull/11
