### ISSUE TITLE
What does‘ todo: per location and per camera’ mean？

### ISSUE THREAD

**Issue by ssssjiang** [cvg/Hierarchical-Localization#92]
Hi, @Skydes
I ran the pipeline on the robotCar dataset and compared the results on visiuallocalization.net, and found that the result data differed a lot in the night scene.
I see "per location and per camera" in the comment info, I guess it's because of this.
Could you please tell me in more detail what this means?
(Sorry, my English is bad.😭 )

Hope to hear from you soon. Thank you so much!

**Comment by Skydes** [comment]
There are 2 tricks to improve image retrieval on RobotCar:
1. Retrieve per camera: global descriptors of the right/left/rear camera are queried only against other descriptors of the corresponding camera.
2. Retrieve per location: RobotCar provides the list of query corresponding to each subset of the 3D model so we can narrow down the set of database descriptors for each query.

These improvements are actually already public in an older branch that contain an earlier version of the pipeline: https://github.com/cvg/Hierarchical-Localization/blob/robotcar/pipelines/RobotCar/robotcar_pairs_from_retrieval.py#L60-L107
I don't have the time right now to clean it up and add it to the new RobotCar pipeline - feel free to submit a PR :)

**Comment by ssssjiang** [comment]
> There are 2 tricks to improve image retrieval on RobotCar:
> 
> 1. Retrieve per camera: global descriptors of the right/left/rear camera are queried only against other descriptors of the corresponding camera.
> 2. Retrieve per location: RobotCar provides the list of query corresponding to each subset of the 3D model so we can narrow down the set of database descriptors for each query.
> 
> These improvements are actually already public in an older branch that contain an earlier version of the pipeline: https://github.com/cvg/Hierarchical-Localization/blob/robotcar/pipelines/RobotCar/robotcar_pairs_from_retrieval.py#L60-L107
> I don't have the time right now to clean it up and add it to the new RobotCar pipeline - feel free to submit a PR :)

Thank you for your reply!😃
I'll try to retrieve per camera. 
Retriveve per location... Is it perhaps not reasonable to use the sum of the localization results on the submaps to represent the localization results on the whole large-scale map?😶

**Comment by ssssjiang** [comment]
> There are 2 tricks to improve image retrieval on RobotCar:
> 
> 1. Retrieve per camera: global descriptors of the right/left/rear camera are queried only against other descriptors of the corresponding camera.
> 2. Retrieve per location: RobotCar provides the list of query corresponding to each subset of the 3D model so we can narrow down the set of database descriptors for each query.
> 
> These improvements are actually already public in an older branch that contain an earlier version of the pipeline: https://github.com/cvg/Hierarchical-Localization/blob/robotcar/pipelines/RobotCar/robotcar_pairs_from_retrieval.py#L60-L107
> I don't have the time right now to clean it up and add it to the new RobotCar pipeline - feel free to submit a PR :)

Thank you for your reply!smiley
I'll try to retrieve per camera and retriveve per location.😃
(Does this also suggest that I can narrow down the matches by dividing the subgraphs to solve the problem of duplication of some scenes?😶)

**Comment by Skydes** [comment]
Image retrieval defines the image pairs that will be matched, so yes these improvements should reduce the number of incorrect matches.

**Comment by ssssjiang** [comment]
> Image retrieval defines the image pairs that will be matched, so yes these improvements should reduce the number of incorrect matches.

Thank you for your reply! You are my role model.
