### ISSUE TITLE
Issue while working with Docker Container 

### ISSUE THREAD

**Issue by kjyothiswaroop** [cvg/Hierarchical-Localization#93]
Hello Everyone!

So I was using the docker container to work with hloc since installing COLMAP on my system was crashing the system.

While working with docker image I am facing the following error in the pipeline_Aachen.py: 

![Screenshot from 2021-08-25 16-50-45](https://user-images.githubusercontent.com/51844889/130781809-cabef2d8-07f2-4ec6-91d9-bb51671123fe.png)

Now here when I checked the /app/hloc/extractors/superpoint.py  it was loading the pre-trained models from /app/third-party/SuperGluePretrained Model.

Now in the Github repository, this location is pointed to the external repository of Superglue but in the docker container, the folder is empty.

So how should I proceed to work with this? Should I be downloading the pre-trained models from Github and uploading them in the docker image?

**Comment by Skydes** [comment]
Did you pull submodules with `git submodule update --init --recursive` ?

**Comment by kjyothiswaroop** [comment]
Aah that's the mistake, sorry to bother you. Did it now. Thank you very much for the swift response
