### ISSUE TITLE
About The Multi-Camera In RobotCar v2 Dataset

### ISSUE THREAD

**Issue by ThompsonHe** [cvg/Hierarchical-Localization#95]
Sorry for bothering, in the leader board i saw you have two submissions on RobotCar V2, one is sing-camera and the other is multi-camera, could you please tell me the different between them? And in your hloc pipeline implementation of robotcar v2, is that the implementation of single camera?   Hoping for your reply, thank you AND BEST REGARDS!

**Comment by Skydes** [comment]
As described in the info box of the multi-camera submission:
> The pose is estimated for the camera rig using RANSAC+GP3P.

hloc currently supports only single-camera localization, but we have a demo of multi-camera localization for our new dataset: https://github.com/cvg/visloc-iccv2021 It should be fairly easy to integrate.

**Comment by ThompsonHe** [comment]
> As described in the info box of the multi-camera submission:
> 
> > The pose is estimated for the camera rig using RANSAC+GP3P.
> 
> hloc currently supports only single-camera localization, but we have a demo of multi-camera localization for our new dataset: https://github.com/cvg/visloc-iccv2021 It should be fairly easy to integrate
Appreciated For Your Reply!
