### ISSUE TITLE
Issue with docker with pipeline_Aachen.py

### ISSUE THREAD

**Issue by kjyothiswaroop** [cvg/Hierarchical-Localization#98]
Hello Everyone!

I am trying to replicate the pieline_Aachen.py using the docker container.
I had successfully setup the docker container but am facing issue while downloading the Aachen dataset.

To avoid downloading each file from the link :
[Dataset Link](https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/)

I used the following command to download all the files from the above link into docker:

`wget -r -np -nH --cut-dirs=3 -R index.html  https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/`

Though, the Aachen.db which is 20GB gets downloaded after this process my laptop gets stuck.

Additionally, I had tried to download all the files from the link and upload them into Jupyter a rather tedious process and tried to perform docker commit so as to save the changes and again my laptop is stuck and doesn't move forward.

**Comment by Skydes** [comment]
We have download instructions [here](https://github.com/cvg/Hierarchical-Localization/tree/master/hloc/pipelines/Aachen#installation). Can you try to also exclude `aachen.db`?
```bash
export dataset=datasets/aachen
wget -r -np -nH -R "index.html*,aachen_v1_1.zip,aachen.db,*.info" --cut-dirs=4  https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/ -P $dataset
unzip $dataset/images/database_and_query_images.zip -d $dataset/images
```
