### ISSUE TITLE
Confused On RobotcarV2 reference images and query images

### ISSUE THREAD

**Issue by ThompsonHe** [cvg/Hierarchical-Localization#99]
Sorry for bothering, I am now confused at robotcarV2's data split of reference images and query images.[refer to the link please](https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/RobotCar-Seasons/). I am wondering how can i obtain the reference images and the query images of robotcar v2? Can they be obtained from robotcar_v2_test.txt and robotcar_v2_train.txt of the Link? Looking For Your Reply and Best Regards!

**Comment by Skydes** [comment]
Queries of RobotCar v2 are a subset of those of the v1. So far I have used the v1 split when evaluating the v2, but in theory you could add images from `robotcar_v2_train.txt` to the database in order to improve the localization performance.
